'use strict';
// GBR research views: all aggregates are recomputed from the selected records.
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=(n,d=2)=>Number.isFinite(+n)?Number(n).toFixed(d):'—';
let all=[],selected=[],tab='overview',page=0,groupPages={};const LIMIT=60;
const qualityName=['','Bad','Below average','Average','Above average','Good'];const numericFields=[['encoder_cfg','Encoder CFG'],['top_k','Top-k'],['sampler_cfg','Sampler CFG'],['sampler_steps','Sampler steps'],['caption_words','Caption words'],['lyrics_words','Lyrics words'],['lyric_sections','Lyric sections'],['avg_lyric_line_words','Words per lyric line']];
const q=r=>Number(r.quality_score)||0;const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN;
const grade=n=>`<span class="quality q${n}">${n}</span>`;
const names=(key,rs=all)=>[...new Set(rs.map(x=>x[key]).filter(x=>x!==null&&x!==undefined&&x!==''))].sort((a,b)=>String(a).localeCompare(String(b)));
function fillSelect(id,values){const el=$(id),current=el.value;while(el.options.length>1)el.remove(1);values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.append(o)});el.value=values.includes(current)?current:''}
function updateOptions(){fillSelect('song',names('title'));fillSelect('cluster',names('cluster'));fillSelect('version',names('version',$('cluster').value?all.filter(x=>x.cluster===$('cluster').value):all))}
function filter(){const t=$('search').value.toLowerCase().trim(),song=$('song').value,cluster=$('cluster').value,version=$('version').value,rating=$('quality').value,pub=$('publication').value;selected=all.filter(r=>(!t||[r.title,r.cluster,r.version,r.audio_file,r.yaml_file].some(v=>String(v??'').toLowerCase().includes(t)))&&(!song||r.title===song)&&(!cluster||r.cluster===cluster)&&(!version||r.version===version)&&(!rating||String(q(r))===rating)&&(!pub||String(Number(r.published)||0)===pub));page=0;groupPages={};$('filteredCounter').textContent=`${selected.length.toLocaleString()} / ${all.length.toLocaleString()} GENERATIONS`;metrics();render()}
function metrics(){const n=selected.length,analysed=selected.filter(r=>r.duration!=null).length,meanRating=mean(selected.map(q));const vals=[['GENERATIONS',n.toLocaleString(),'selected records'],['MEAN LISTENING SCORE',Number.isFinite(meanRating)?fmt(meanRating)+' / 5':'—','human assessments'],['RATED 4–5',n?fmt(100*selected.filter(r=>q(r)>=4).length/n,1)+'%':'—','above average or good'],['AUDIO PROFILED',analysed.toLocaleString(),n?fmt(analysed/n*100,1)+'% of selected':'no selections'],['PUBLISHED IN GBR',selected.filter(r=>r.published).length.toLocaleString(),'matching catalogue entries']];$('meters').innerHTML=vals.map(([label,v,note])=>`<div class="meter"><small>${label}</small><strong>${v}</strong><span>${note}</span></div>`).join('')}
function group(key,rows=selected){const m=new Map;rows.forEach(r=>{const k=typeof key==='function'?key(r):r[key];if(k===null||k===undefined||k==='')return;const id=String(k);if(!m.has(id))m.set(id,{name:id,n:0,sum:0,good:0,bad:0});let x=m.get(id);x.n++;x.sum+=q(r);x.good+=q(r)>=4;x.bad+=q(r)<=2});return [...m.values()].map(x=>({...x,avg:x.sum/x.n,success:x.good/x.n*100,fail:x.bad/x.n*100}))}
function sortedGroups(key,order='average',limit=18){return group(key).sort((a,b)=>order==='count'?b.n-a.n:order==='worst'?a.avg-b.avg:b.avg-a.avg).slice(0,limit)}
function axisSvg(title,arr,{maxBars=16,metric='avg',fixedMax,reverse=false}={}){if(!arr.length)return empty('No matching measurements');arr=arr.slice(0,maxBars);const W=730,H=Math.max(255,arr.length*31+52),left=190,right=80,iw=W-left-right,lim=fixedMax??Math.max(...arr.map(x=>x[metric]),1),base=reverse?lim:0;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}">`;
for(let i=0;i<=5;i++){const x=left+iw*i/5;svg+=`<line class="gridline" x1="${x}" y1="15" x2="${x}" y2="${H-28}"/><text x="${x}" y="${H-6}" text-anchor="middle">${fmt(lim*i/5,lim<=5?1:0)}</text>`}
arr.forEach((r,i)=>{const y=20+i*31,bar=Math.max(0,Math.min(1,r[metric]/lim))*iw;svg+=`<text x="${left-12}" y="${y+14}" text-anchor="end">${esc(r.name.length>27?r.name.slice(0,25)+'…':r.name)}</text><rect class="bar" x="${left}" y="${y}" width="${bar}" height="20" rx="2"><title>${esc(r.name)}: ${fmt(r[metric])} (${r.n} tracks)</title></rect><text x="${left+bar+8}" y="${y+15}">${fmt(r[metric])}  ·  n=${r.n}</text>`});return svg+'</svg>'}
function pieRatings(){const count=[1,2,3,4,5].map(v=>selected.filter(x=>q(x)===v).length),total=count.reduce((a,b)=>a+b,0),colors=['#a85e54','#bd8760','#b6a06a','#8daa81','#629b72'];if(!total)return empty('No rated generations');let pos=0;const segments=count.map((v,i)=>{const start=pos/total*100;pos+=v;return `${colors[i]} ${start}% ${pos/total*100}%`}).join(',');return `<div style="display:grid;grid-template-columns:200px 1fr;gap:20px;align-items:center"><div style="height:200px;width:200px;border-radius:50%;background:conic-gradient(${segments});position:relative"><div style="position:absolute;inset:38px;border-radius:50%;background:#161a14;display:grid;place-items:center;font:34px Georgia,serif">${total}</div></div><div>${count.map((n,i)=>`<div style="display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #353b30;padding:9px 4px;font-size:12px"><span><i style="background:${colors[i]};display:inline-block;width:10px;height:10px;margin-right:10px"></i>${i+1} · ${qualityName[i+1]}</span><b>${n} · ${fmt(n/total*100,1)}%</b></div>`).join('')}</div></div>`}
function pane(title,inside,note='',full=false){return `<article class="pane${full?' full':''}"><header><h3>${esc(title)}</h3><span class="sub">${esc(note)}</span></header>${inside}</article>`}
function empty(msg){return `<div class="emptystate">${esc(msg)}</div>`}
function table(cols,rows,{click=false}={}){if(!rows.length)return empty('No records match the current selection');return `<div class="twrap"><table class="datatable"><thead><tr>${cols.map(c=>`<th class="${c.num?'num':''}">${esc(c.name)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr ${click?`data-id="${esc(r.id)}"`:''}>${cols.map(c=>`<td class="${c.num?'num':''}">${c.f?c.f(r):esc(r[c.key]??'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const groupCols=[{name:'Category',key:'name'},{name:'Tracks',key:'n',num:true},{name:'Mean',f:r=>fmt(r.avg),num:true},{name:'4–5',f:r=>fmt(r.success,1)+'%',num:true},{name:'1–2',f:r=>fmt(r.fail,1)+'%',num:true}];
function lineChart(key,items){if(items.length<2)return empty('At least two parameter values are needed');items=items.slice().sort((a,b)=>Number(a.name)-Number(b.name));let W=740,H=290,L=42,R=30,B=44,T=20,inner=W-L-R,step=inner/Math.max(1,items.length-1);let s=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Average rating by ${esc(key)}">`;for(let i=1;i<=5;i++){const y=T+(5-i)*(H-T-B)/4;s+=`<line class="gridline" x1="${L}" x2="${W-R}" y1="${y}" y2="${y}"/><text x="${L-10}" y="${y+4}" text-anchor="end">${i}</text>`}const pts=items.map((r,i)=>[L+i*step,T+(5-r.avg)*(H-T-B)/4]);s+=`<path class="line" d="${pts.map(([x,y],i)=>(i?'L':'M')+x+','+y).join(' ')}"/>`;pts.forEach(([x,y],i)=>{let item=items[i];s+=`<circle class="dot" cx="${x}" cy="${y}" r="6"><title>${esc(item.name)}: ${fmt(item.avg)} / 5, ${item.n} tracks</title></circle><text x="${x}" y="${H-18}" text-anchor="middle">${esc(item.name)}</text>`});return s+'</svg>'}
function chartGroup(key,label,{order='average',limit=15,metric='avg',fixedMax=5}={}){const a=sortedGroups(key,order,limit);return `<div class="plot">${axisSvg(label,a,{metric,fixedMax})}</div>`}
function overview(){const clusters=sortedGroups('cluster','count',13),songs=sortedGroups('title','worst',15);return `<div class="layout wide-first">${pane('Quality distribution',pieRatings(),'All five listening grades')}${pane('Largest genre clusters',`<div class="plot">${axisSvg('Clusters',clusters,{fixedMax:5})}</div>`,'Mean / 5 with sample sizes')}${pane('Songs with the lowest averages',`<div class="plot">${axisSvg('Song difficulty',songs,{fixedMax:5})}</div>`,'Exploratory · watch sample sizes')}${pane('Research guide',`<p class="note">The charts update with every filter. A high mean based on one track is not as reliable as the same mean across hundreds of tracks. Compare a song within its genre and parameter settings before attributing poor results to the composition.</p><p class="note">Open <strong>Parameter lab</strong> for generation controls, <strong>Text structure</strong> for non-semantic caption and lyric measurements, and <strong>Generation archive</strong> to inspect individual attempts.</p>`,'Interpretation notes')}</div>`}
function comboHeat(){const records=selected.filter(r=>r.sampler&&r.scheduler);const sam=[...new Set(records.map(x=>x.sampler))].sort(),sch=[...new Set(records.map(x=>x.scheduler))].sort();if(!sam.length||!sch.length)return empty('No sampler/scheduler pairs found');const grid=(sam.length*sch.length>50)?'Showing all recorded pairs.':`Cell colours reflect mean quality, not certainty.`;const head=`<div class="heatrow header" style="--n:${sch.length}"><div>Sampler / scheduler</div>${sch.map(x=>`<div title="${esc(x)}">${esc(x)}</div>`).join('')}</div>`;const cells=sam.map(a=>`<div class="heatrow" style="--n:${sch.length}"><div class="heatlabel">${esc(a)}</div>${sch.map(b=>{const x=records.filter(r=>r.sampler===a&&r.scheduler===b);if(!x.length)return `<div class="heatcell" style="background:#252921">—</div>`;const m=mean(x.map(q)),light=Math.round((m-1)/4*37+13);return `<div class="heatcell" title="${x.length} tracks; mean ${fmt(m)}" style="background:hsl(43 45% ${light}%)">${fmt(m)}<small style="display:block;opacity:.8">n=${x.length}</small></div>`}).join('')}</div>`).join('');return `<div style="overflow:auto">${head}${cells}</div><p class="note">${grid}</p>`}
function parameters(){const g=group('sampler_steps').sort((a,b)=>Number(a.name)-Number(b.name));const scalar=numericFields.slice(0,4).map(([k,title])=>pane(title,`<div class="plot">${lineChart(title,group(k))}</div>`, 'Mean score · observed values'));const cfg=group(r=>r.encoder_cfg==null||r.sampler_cfg==null?'Unknown':String(Math.round((r.encoder_cfg-r.sampler_cfg)*100)/100));return `<div class="layout">${pane('Sampler × scheduler',comboHeat(),'Mean score / 5 · n = observed tracks',true)}${scalar.join('')}${pane('Encoder minus sampler CFG',`<div class="plot">${axisSvg('CFG difference',cfg.sort((a,b)=>b.n-a.n),{fixedMax:5})}</div>`,'Difference, mean and sample size')}${pane('Algorithm comparison',table(groupCols,group(r=>[r.sampler,r.scheduler].filter(Boolean).join(' / ')).sort((a,b)=>b.n-a.n)),'Sampler / scheduler pairs')}</div>`}
function songs(){return `<div class="layout">${pane('Song performance',`<div class="plot">${axisSvg('Song means',sortedGroups('title','count',22),{fixedMax:5,maxBars:22})}</div>`,'22 most frequently reviewed songs')}${pane('Cluster performance',`<div class="plot">${axisSvg('Cluster means',sortedGroups('cluster','count',22),{fixedMax:5,maxBars:22})}</div>`,'Mean listening score')}${pane('Song ranking',table(groupCols,group('title').sort((a,b)=>b.n-a.n)),'All songs · largest samples first')}${pane('Version ranking',table(groupCols,group(r=>[r.cluster,r.version].filter(Boolean).join(' / ')).sort((a,b)=>b.n-a.n)),'Cluster + version pairs')}</div>`}
function text(){const pairs=[['caption_words','Caption word count'],['caption_avg_word_length','Average caption word length'],['lyrics_words','Lyric word count'],['lyrics_avg_word_length','Average lyric word length'],['lyric_sections','Number of lyric sections'],['avg_lyric_line_words','Words per sung lyric line']];return `<div class="layout">${pairs.map(([k,title])=>{const rows=selected.filter(r=>Number.isFinite(Number(r[k]))&&r[k]!=null);if(!rows.length)return pane(title,empty('No text measurements'));const values=rows.map(r=>Number(r[k])).sort((a,b)=>a-b),max=values[values.length-1],min=values[0],bins=8,step=(max-min||1)/bins;const buckets=Array.from({length:bins},(_,i)=>({name:fmt(min+i*step,step<1?1:0)+'–'+fmt(min+(i+1)*step,step<1?1:0),n:0,sum:0}));rows.forEach(r=>{let idx=Math.min(bins-1,Math.floor((Number(r[k])-min)/step));buckets[idx].sum+=q(r);buckets[idx].n++});const g=buckets.filter(b=>b.n).map(b=>({...b,avg:b.sum/b.n}));return pane(title,`<div class="plot">${axisSvg(title,g,{fixedMax:5,maxBars:8})}</div>`,'Eight equal-width bands · mean score / 5')}).join('')}</div>`}
function audio(){const withAudio=selected.filter(x=>x.duration!=null);if(!withAudio.length)return `<div class="layout">${pane('Audio profiling pending',`<div class="emptystate">No audio profiles in the current selection.<p class="note">The imported database only contains audio measurements when an existing .audio.json is found, or when external FLAC profiling is explicitly enabled in the refresh command.</p></div>`,'Original FLACs stay outside Git',true)}</div>`;const fields=[['bpm','Estimated tempo (BPM)'],['rms_db','RMS loudness (dB)'],['onset_density','Onset density'],['energy_std','Energy variation'],['bass_mean','Average bass activity'],['brightness_mean','Average brightness']];return `<div class="layout">${fields.map(([key,title])=>{const rows=withAudio.filter(r=>r[key]!=null),vals=rows.map(r=>+r[key]),min=Math.min(...vals),max=Math.max(...vals),step=(max-min||1)/8,buckets=Array.from({length:8},(_,i)=>({name:fmt(min+i*step,1)+'–'+fmt(min+(i+1)*step,1),n:0,sum:0}));rows.forEach(r=>{const b=buckets[Math.min(7,Math.floor((r[key]-min)/step))];b.n++;b.sum+=q(r)});return pane(title,`<div class="plot">${axisSvg(title,buckets.filter(x=>x.n).map(x=>({...x,avg:x.sum/x.n})),{fixedMax:5,maxBars:8})}</div>`,`${rows.length} profiled generations`) }).join('')}</div>`}
function archive(){const rows=selected.slice(page*LIMIT,(page+1)*LIMIT);return pane('Generation records',table([{name:'Song',f:r=>`<strong>${esc(r.title||'Untitled')}</strong>`},{name:'Cluster',key:'cluster'},{name:'Version',key:'version'},{name:'Grade',f:r=>grade(q(r))},{name:'Top-k',key:'top_k',num:true},{name:'Steps',key:'sampler_steps',num:true},{name:'Audio',f:r=>r.duration==null?'—':'PROFILED'},{name:'Publication',f:r=>r.published?'GBR':'Research'}],rows,{click:true})+`<div class="pagination"><span>${selected.length?1+page*LIMIT:0}–${Math.min(selected.length,(page+1)*LIMIT)} of ${selected.length}</span><button id="prev" ${page===0?'disabled':''}>‹ PREV</button><button id="next" ${(page+1)*LIMIT>=selected.length?'disabled':''}>NEXT ›</button></div>`,'Select a row to inspect its exact generation parameters',true)}
const info={overview:['GLOBAL RESEARCH','The big picture'],parameters:['GENERATION ENGINE','The parameter laboratory'],songs:['COMPOSITIONS & STYLES','Where does quality change?'],text:['LYRIC & CAPTION METRICS','Structure, not semantics'],audio:['SPECTRAL & RHYTHMIC ANALYSIS','Inside the waveform'],records:['ALL RATED ATTEMPTS','The generation archive']};
function render(){const [kicker,title]=info[tab];$('sectionKicker').textContent=kicker;$('sectionTitle').textContent=title;$('sectionContext').textContent=`${selected.length.toLocaleString()} selected generations`;let content={overview,parameters,songs,text,audio,records:archive}[tab]();$('content').innerHTML=content;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));const prev=$('prev'),next=$('next');if(prev)prev.onclick=()=>{page--;render()};if(next)next.onclick=()=>{page++;render()};document.querySelectorAll('tr[data-id]').forEach(tr=>tr.addEventListener('click',()=>detail(tr.dataset.id)))}
function detail(id){const r=all.find(x=>x.id===id);if(!r)return;const fields=[['Rating',`${q(r)} / 5 · ${qualityName[q(r)]}`],['Cluster',r.cluster],['Version',r.version],['Model',r.model],['Encoder CFG',r.encoder_cfg],['Top-k',r.top_k],['Sampler CFG',r.sampler_cfg],['Sampler steps',r.sampler_steps],['Sampler',r.sampler],['Scheduler',r.scheduler],['Encoder seed',r.encoder_seed],['Sampler seed',r.sampler_seed],['Caption words',r.caption_words],['Lyric words',r.lyrics_words],['Lyric sections',r.lyric_sections],['Duration (seconds)',r.duration],['Tempo (BPM)',r.bpm],['RMS loudness (dB)',r.rms_db],['Onset density',r.onset_density],['Published',r.published?'Yes':'No'],['Audio filename',r.audio_file],['YAML filename',r.yaml_file]];$('detail').innerHTML=`<h2>${esc(r.title||'Untitled')}</h2><p class="note">${esc(r.cluster||'Uncategorised')} / ${esc(r.version||'Unspecified')}</p><div class="detailgrid">${fields.map(([label,v])=>`<div class="detailbox"><small>${esc(label)}</small><strong>${esc(v??'—')}</strong></div>`).join('')}</div><h3>Lyric sections</h3><div class="detailgrid">${Object.entries(r.section_counts||{}).map(([name,n])=>`<div class="detailbox"><small>${esc(name)}</small><strong>${esc(n)}</strong></div>`).join('')||'<p class="note">No section details</p>'}</div>`;$('shade').hidden=false;$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false')}
function close(){ $('shade').hidden=true;$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}
function init(){document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;page=0;render()}));['search','song','cluster','version','quality','publication'].forEach(k=>$(k).addEventListener(k==='search'?'input':'change',()=>{if(k==='cluster')updateOptions();filter()}));$('reset').onclick=()=>{['search','song','cluster','version','quality','publication'].forEach(k=>$(k).value='');filter()};$('closeDrawer').onclick=close;$('shade').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}
async function load(){init();try{const url='../data/analytics/generations.json';const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status+' loading '+url);const data=await response.json();if(!Array.isArray(data.generations))throw new Error('Invalid export format');all=data.generations;$('stamp').textContent='EXPORTED '+new Date(data.generated_at).toLocaleString();updateOptions();filter()}catch(err){$('content').innerHTML=empty(`Dataset unavailable: ${err.message}. Run the analytics refresh, then serve GBR over HTTP.`);$('stamp').textContent='NO SIGNAL';console.error(err)}}load();
