'use strict';
/* GBR Experiment Floor. Uses the same filtered generation rows as the existing analytics. */
const EX_FIELDS=[
 ['sampler_steps','Sampling steps','number'],['encoder_cfg','Encoder CFG','number'],['sampler_cfg','Sampler CFG','number'],['top_k','Top K','number'],
 ['sampler','Sampler','category'],['scheduler','Scheduler','category'],['text_encoder','Text encoder','category'],['dit','DiT precision','category'],
 ['caption_source','Caption source','category'],['cluster','Genre cluster','category'],['version','Style / version','category'],['title','Composition','category'],
 ['caption_words','Caption words','number'],['lyrics_words','Lyric words','number'],['bpm','Estimated BPM','number'],['duration','Duration (seconds)','number'],
 ['energy_mean','Signal energy','number'],['bass_mean','Bass energy','number'],['brightness_mean','Brightness','number'],['onset_density','Onset density','number'],
 ['quality_score','Listening grade','number']
];
const EF=Object.fromEntries(EX_FIELDS.map(([id,label,type])=>[id,{id,label,type}]));
const ep={x:'sampler_steps',y:'quality_score',split:'none',mode:'auto',metric:'mean',threshold:5,selected:null};
const ECLR=['#dfb56b','#84b6a0','#cb8373','#a996cc','#e3a6c2','#81aeca','#dbc789','#c8c1a9'];
const EFESC=x=>String(x==null?'Unknown':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const efNumber=(r,k)=>{let n=Number(r[k]);return r[k]!==null&&r[k]!==''&&Number.isFinite(n)?n:null};
const efValue=(r,k)=>EF[k]?.type==='number'?efNumber(r,k):String(r[k]??'Unknown');
function efRows(){return filtered.filter(r=>Number.isFinite(+r.quality_score)&&r.quality_score!==null&&efValue(r,ep.x)!==null&&efValue(r,ep.y)!==null).slice()}
function efStats(rs){const grades=rs.map(r=>+r.quality_score).filter(Number.isFinite);return {n:grades.length,mean:grades.length?grades.reduce((a,b)=>a+b,0)/grades.length:0,accept:grades.length?grades.filter(a=>a>=4).length/grades.length:0,zero:grades.length?grades.filter(a=>a===0).length/grades.length:0}}
function efMetric(a){return ep.metric==='accept'?a.accept*100:ep.metric==='zero'?a.zero*100:a.mean}
function efMetricLabel(){return {mean:'Mean listening grade / 5',accept:'Rated 4–5 (%)',zero:'Unlistenable (%)'}[ep.metric]}
function efScale(v,a,b,l,r){return l+(v-a)/(b-a||1)*(r-l)}
function efGroup(rs,key){const m=new Map();for(const r of rs){const k=String(efValue(r,key));if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m].map(([name,items])=>({name,items,...efStats(items)}))}
function efCategories(rs,key,limit=13){const g=efGroup(rs,key).sort((a,b)=>b.n-a.n);return g.slice(0,limit)}
function efAxisKey(key){return EF[key]?.label||key}
function efVisibleType(){if(ep.mode!=='auto'){if(ep.mode==='scatter'&&(EF[ep.x].type!=='number'||EF[ep.y].type!=='number'))return 'distribution';return ep.mode;}const a=EF[ep.x].type,b=EF[ep.y].type;return a==='category'&&b==='category'?'heat':a==='number'&&b==='number'?'scatter':'distribution'}
function efOptions(selected,without=''){return EX_FIELDS.filter(a=>a[0]!==without).map(([id,label])=>`<button class="ef-choice ${selected===id?'chosen':''}" data-choose="${id}" type="button"><span class="ef-lamp"></span>${EFESC(label)}</button>`).join('')}
function efSelector(title,current,slot){return `<div class="ef-channel" data-channel="${slot}"><div class="ef-channel-kicker">${title}</div><button class="ef-knob" type="button" data-open-choose="${slot}" aria-label="Change ${title}"><span>${EFESC(efAxisKey(current))}</span><b>↕</b></button></div>`}
function efGroupSelector(){return `<button class="ef-split-button" id="efSplit"><span class="ef-lamp"></span>${ep.split==='none'?'⊕ ADD A THIRD DIMENSION':`◈ ${EFESC(efAxisKey(ep.split))}`}</button>`}
function explorerView(){const rs=efRows();const split=ep.split==='none'?[]:efCategories(rs,ep.split,8);return `<section class="ef-shell"><div class="ef-topline"><span><span class="ef-live"></span> EXPERIMENT FLOOR · GBR</span><span>${rs.length.toLocaleString()} MATCHING GENERATIONS / ${filtered.length.toLocaleString()} FILTERED</span><button type="button" id="efFilter">FILTERS ☷</button></div><div class="ef-instrument"><div class="ef-sidebar"><div class="ef-stamp">01 / RELATIONSHIP</div><div class="ef-heading">Find the<br><i>interesting bits.</i></div><p>Pick a property. Compare it to another. Add a third to expose the difference.</p>${efSelector('HORIZONTAL / FACTOR',ep.x,'x')}${efSelector('VERTICAL / RESPONSE',ep.y,'y')}<div class="ef-secondary"><span>RESULT MEASURE</span><div class="ef-toggle">${[['mean','MEAN'],['accept','4–5 %'],['zero','0 %']].map(([id,label])=>`<button type="button" data-metric="${id}" class="${ep.metric===id?'active':''}">${label}</button>`).join('')}</div></div><div class="ef-secondary"><span>EVIDENCE MINIMUM</span><div class="ef-toggle">${[1,5,10,20].map(n=>`<button type="button" data-threshold="${n}" class="${ep.threshold===n?'active':''}">${n}</button>`).join('')}</div></div><button type="button" id="efSwap" class="ef-small-action">⇄ SWAP AXES</button><button type="button" id="efReset" class="ef-small-action">↺ RESET VIEW</button></div><div class="ef-main"><div class="ef-canvas-head"><div><small>02 / SONIC EVIDENCE</small><h2>${EFESC(efAxisKey(ep.x))} <em>×</em> ${EFESC(efAxisKey(ep.y))}</h2></div><div class="ef-readout"><span>VISUAL MODE</span><select id="efMode"><option value="auto" ${ep.mode==='auto'?'selected':''}>AUTO</option><option value="scatter" ${ep.mode==='scatter'?'selected':''}>SCATTER</option><option value="distribution" ${ep.mode==='distribution'?'selected':''}>GROUPED DOTS</option><option value="heat" ${ep.mode==='heat'?'selected':''}>HEATMAP</option></select></div></div><div id="efGraphic" class="ef-graphic"></div><div class="ef-bottom"><div class="ef-breakdown">${efGroupSelector()}<div class="ef-legend">${split.map((g,i)=>`<span title="${g.n} observations"><i style="background:${ECLR[i%ECLR.length]}"></i>${EFESC(g.name)} <small>n=${g.n}</small></span>`).join('')}</div></div><div class="ef-explain" id="efExplain"></div></div></div></div><div class="ef-insights"><div><small>03 / READING THE EXPERIMENT</small><h3>What the evidence says.</h3></div><div id="efFindings" class="ef-findings"></div></div><div class="ef-foot">DOTS = INDIVIDUAL GENERATIONS · MEASUREMENTS = OBSERVED · ALL RELATIONSHIPS ARE ASSOCIATIONS, NOT PROOF OF CAUSATION</div></section><div id="efPalette" class="ef-palette" hidden><div class="ef-palette-head"><strong id="efPaletteTitle">CHOOSE A PARAMETER</strong><button id="efPaletteClose" type="button">CLOSE ×</button></div><input id="efSearch" type="search" placeholder="Find a parameter…"><div id="efChoices" class="ef-choices"></div></div>`}
function efSVGHeader(W,H,l,t,b){return `<rect x="0" y="0" width="${W}" height="${H}" fill="transparent"/><line x1="${l}" y1="${H-b}" x2="${W-18}" y2="${H-b}" stroke="#887b60" opacity=".55"/><line x1="${l}" y1="${t}" x2="${l}" y2="${H-b}" stroke="#887b60" opacity=".55"/>`}
function efScatter(rs){const W=920,H=485,L=76,T=28,B=72,R=30;
 const all=rs.length>1500?rs.filter((_,i)=>i%Math.ceil(rs.length/1500)===0):rs;
 const xs=rs.map(r=>efValue(r,ep.x)),ys=rs.map(r=>efValue(r,ep.y));let xMin=Math.min(...xs),xMax=Math.max(...xs),yMin=Math.min(...ys),yMax=Math.max(...ys);if(xMin===xMax)xMax=xMin+1;if(yMin===yMax)yMax=yMin+1;
 const x=v=>efScale(v,xMin,xMax,L,W-R),y=v=>efScale(v,yMin,yMax,H-B,T);
 const splitGroups=ep.split==='none'?[]:efCategories(rs,ep.split,8);const color=r=>{if(!splitGroups.length)return ECLR[0];const i=splitGroups.findIndex(g=>String(efValue(r,ep.split))===g.name);return i<0?'#6a6d62':ECLR[i%ECLR.length]};
 let out=efSVGHeader(W,H,L,T,B);
 for(let i=0;i<=5;i++){const value=yMin+(yMax-yMin)*i/5,py=y(value);out+=`<line x1="${L}" x2="${W-R}" y1="${py}" y2="${py}" stroke="#aa956f" opacity=".13"/><text x="${L-13}" y="${py+4}" text-anchor="end" fill="#c2b6a1" font-size="13">${Number(value.toFixed(2))}</text>`;const v=xMin+(xMax-xMin)*i/5;out+=`<text x="${x(v)}" y="${H-B+25}" text-anchor="middle" fill="#c2b6a1" font-size="13">${Number(v.toFixed(2))}</text>`}
 // deterministic displacement for discrete integer scores, not noise-based random positioning
 const discrete=rs.every(r=>Number.isInteger(+r[ep.y])&&+r[ep.y]>=0&&+r[ep.y]<=5);
 out+=all.map((r,i)=>{const py=y(efValue(r,ep.y))+(discrete?((i*37%19)-9)*.82:0);const px=x(efValue(r,ep.x));return `<circle data-ef-record="${EFESC(r.id)}" cx="${px.toFixed(2)}" cy="${py.toFixed(2)}" r="4.4" fill="${color(r)}" fill-opacity=".61" stroke="#151915" stroke-width=".55"><title>${EFESC(r.audio_file||r.title)} · ${efAxisKey(ep.x)} ${efValue(r,ep.x)} · ${efAxisKey(ep.y)} ${efValue(r,ep.y)} · grade ${r.quality_score}</title></circle>`}).join('');
 out+=`<text x="${W/2}" y="${H-12}" text-anchor="middle" fill="#d8bb83" font-size="15">${EFESC(efAxisKey(ep.x))}</text><text x="18" y="${H/2}" transform="rotate(-90 18 ${H/2})" text-anchor="middle" fill="#d8bb83" font-size="15">${EFESC(efAxisKey(ep.y))}</text>`;
 return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scatter plot: ${EFESC(efAxisKey(ep.x))} versus ${EFESC(efAxisKey(ep.y))}">${out}</svg><p class="ef-chartnote">Each dot is an individual generation. Overlapping dots can conceal repeats. Vertical jitter is used only for discrete grades; chart values remain unchanged.</p>`}
function efDistribution(rs){let cat=EF[ep.x].type==='category'?ep.x:EF[ep.y].type==='category'?ep.y:null;let num=cat===ep.x?ep.y:ep.x;if(!cat){ // bin horizontal numeric field for quality distributions
 cat=ep.x;num=ep.y;
 const vals=rs.map(r=>+r[cat]);const min=Math.min(...vals),max=Math.max(...vals),width=(max-min||1)/8;
 rs=rs.map(r=>({...r,[cat]:(min+Math.min(7,Math.floor((+r[cat]-min)/width))*width).toFixed(2)+'–'+(min+(Math.min(7,Math.floor((+r[cat]-min)/width))+1)*width).toFixed(2)}));
 }
 const cats=efCategories(rs,cat,12);if(!cats.length)return '<div class="ef-empty">No matching values.</div>';
 const maxValue=num==='quality_score'?5:Math.max(...rs.map(r=>+r[num]));const minValue=num==='quality_score'?0:Math.min(...rs.map(r=>+r[num]));
 return `<div class="ef-distributions">${cats.map((g,j)=>{const values=g.items.map(r=>+r[num]).filter(Number.isFinite).sort((a,b)=>a-b),m=values.reduce((a,b)=>a+b,0)/values.length;const pos=v=>Math.max(0,Math.min(100,100*(v-minValue)/(maxValue-minValue||1)));const sample=values.length>75?values.filter((_,i)=>i%Math.ceil(values.length/75)===0):values;return `<div class="ef-dist-row"><span class="ef-dist-name">${EFESC(g.name)}<small>n=${g.n}</small></span><div class="ef-dist-track"><div class="ef-dist-rail"></div>${sample.map((v,i)=>`<i title="${EFESC(g.name)}: ${v}" style="left:${pos(v)}%;top:${9+(i*29%19)}px;background:${ECLR[j%ECLR.length]}"></i>`).join('')}<b style="left:${pos(m)}%" title="Mean ${m.toFixed(2)}"></b></div><strong>${m.toFixed(2)}</strong></div>`}).join('')}</div><div class="ef-scale"><span>${Number(minValue.toFixed(2))}</span><span>${EFESC(efAxisKey(num))} →</span><span>${Number(maxValue.toFixed(2))}</span></div><p class="ef-chartnote">Dots show individual observed values; gold vertical marks indicate group means. Categories are ordered by sample size, not rank.</p>`}
function efHeat(rs){const x=efCategories(rs,ep.x,10),y=efCategories(rs,ep.y,10);if(!x.length||!y.length)return '<div class="ef-empty">No matching cells.</div>';const sampleCount=rs.length;let grid=`<div class="ef-heat-wrap"><table class="ef-heat"><thead><tr><th>${EFESC(efAxisKey(ep.y))} ↓ / ${EFESC(efAxisKey(ep.x))} →</th>${x.map(a=>`<th title="${EFESC(a.name)}">${EFESC(a.name)}</th>`).join('')}</tr></thead><tbody>`;
 for(const yy of y){grid+=`<tr><th>${EFESC(yy.name)}</th>`;for(const xx of x){const intersect=rs.filter(r=>String(efValue(r,ep.x))===xx.name&&String(efValue(r,ep.y))===yy.name),s=efStats(intersect),value=efMetric(s),max=ep.metric==='mean'?5:100;grid+=`<td title="${EFESC(xx.name)} / ${EFESC(yy.name)} — n=${s.n}; mean ${s.mean.toFixed(2)}; 4–5 ${(s.accept*100).toFixed(1)}%" class="${s.n<ep.threshold?'ef-thin':''}" style="background:${s.n?`rgba(218,170,88,${(.06+.70*value/max).toFixed(2)})`:'transparent'}">${s.n?`<b>${value.toFixed(ep.metric==='mean'?2:1)}${ep.metric==='mean'?'':'%'}</b><small>n=${s.n}</small>`:'<span>·</span>'}</td>`}grid+='</tr>'}return grid+'</tbody></table></div><p class="ef-chartnote">Darker / brighter cells show '+EFESC(efMetricLabel())+'. Cells marked with low N lack sufficient observations. Empty cells are untested, not poor results. Showing '+sampleCount+' total generations.</p>'}
function efFindings(rs){const s=efStats(rs);if(!rs.length)return '<div class="ef-empty">No qualifying data; relax filters or choose other properties.</div>';
 let xGroup=EF[ep.x].type==='category'?efCategories(rs,ep.x,25):[];
 let findings=[];findings.push({name:'EVIDENCE IN VIEW',title:`${s.n.toLocaleString()} generations`,copy:`Mean grade ${s.mean.toFixed(2)} / 5 · ${(s.accept*100).toFixed(1)}% scored 4–5. These are observed ratings, not model predictions.`});
 if(xGroup.length>1){const reliable=xGroup.filter(g=>g.n>=ep.threshold).sort((a,b)=>b.mean-a.mean);if(reliable.length>=2){const best=reliable[0],worst=reliable[reliable.length-1];findings.push({name:'OBSERVED SPREAD',title:`${EFESC(best.name)} · ${best.mean.toFixed(2)}`,copy:`Highest mean among groups with at least ${ep.threshold} ratings. Difference from ${EFESC(worst.name)}: ${(best.mean-worst.mean).toFixed(2)} points. This is not a controlled effect.`})}const sparse=xGroup.filter(g=>g.n<ep.threshold);if(sparse.length)findings.push({name:'GAP DETECTED',title:`${sparse.length} thinly tested groups`,copy:`Fewer than ${ep.threshold} observations in ${sparse.slice(0,3).map(g=>EFESC(g.name)).join(', ')}. More matched experiments are needed.`})}
 else if(EF[ep.x].type==='number'){const value=rs.map(r=>efValue(r,ep.x));const lo=Math.min(...value),hi=Math.max(...value),step=(hi-lo||1)/5;const buckets=Array.from({length:5},(_,i)=>{let a=rs.filter(r=>Math.min(4,Math.floor((efValue(r,ep.x)-lo)/step))===i);return {...efStats(a),label:`${(lo+i*step).toFixed(1)}–${(lo+(i+1)*step).toFixed(1)}`}});const valid=buckets.filter(b=>b.n>=ep.threshold).sort((a,b)=>b.mean-a.mean);if(valid.length)findings.push({name:'STRONGEST OBSERVED REGION',title:`${valid[0].label}`,copy:`Mean ${valid[0].mean.toFixed(2)} / 5 across ${valid[0].n} generations. Parameter settings, caption source and genre may confound this comparison.`})}
 if(ep.split!=='none')findings.push({name:'COHORT CONTROL',title:`Split by ${efAxisKey(ep.split)}`,copy:`Check whether a trend survives within each group rather than being driven by the mixture of configurations.`});
 findings.push({name:'INTERPRETATION',title:'Observation ≠ cause',copy:'For parameter recommendations, hold song, caption, encoder, scheduler and seed design constant. Group averages alone do not isolate one parameter.'});
 return findings.slice(0,4).map(f=>`<div class="ef-finding"><small>${f.name}</small><strong>${f.title}</strong><p>${f.copy}</p></div>`).join('')}
function efDraw(){const rs=efRows(),graphic=document.getElementById('efGraphic');if(!graphic)return;const type=efVisibleType();graphic.innerHTML=type==='heat'?efHeat(rs):type==='distribution'?efDistribution(rs):EF[ep.x].type==='number'&&EF[ep.y].type==='number'?efScatter(rs):efDistribution(rs);document.getElementById('efFindings').innerHTML=efFindings(rs);document.getElementById('efExplain').textContent=type==='heat'?'CELL BRIGHTNESS = '+efMetricLabel():type==='scatter'?'EACH DOT = ONE RECORDED GENERATION':'EACH DOT = A MEASURED VALUE';graphic.querySelectorAll('[data-ef-record]').forEach(n=>n.addEventListener('click',()=>detail(n.dataset.efRecord)))}
function wireExplorer(){const q=id=>document.getElementById(id),palette=q('efPalette');let slot='x';const open=(s)=>{slot=s;q('efPaletteTitle').textContent=s==='split'?'ADD ANOTHER DIMENSION':s==='x'?'CHOOSE HORIZONTAL FACTOR':'CHOOSE VERTICAL RESPONSE';palette.hidden=false;q('efSearch').value='';fill();q('efSearch').focus()};const fill=()=>{const term=q('efSearch').value.toLowerCase();let choices=EX_FIELDS.filter(([id,label])=>(id==='none'||label.toLowerCase().includes(term)));q('efChoices').innerHTML=(slot==='split'?'<button data-choose="none" class="ef-choice">✕ NO BREAKDOWN</button>':'')+choices.map(([id,label])=>`<button type="button" data-choose="${id}" class="ef-choice ${(slot==='x'?ep.x:slot==='y'?ep.y:ep.split)===id?'chosen':''}"><span class="ef-lamp"></span>${EFESC(label)}</button>`).join('');q('efChoices').querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{let id=b.dataset.choose;if(slot==='x'&&id===ep.y||slot==='y'&&id===ep.x){const old=ep[slot];ep[slot]=id;ep[slot==='x'?'y':'x']=old}else ep[slot]=id;ep.mode='auto';palette.hidden=true;render()})};
 document.querySelectorAll('[data-open-choose]').forEach(b=>b.onclick=()=>open(b.dataset.openChoose));q('efSplit').onclick=()=>open('split');q('efPaletteClose').onclick=()=>palette.hidden=true;q('efSearch').oninput=fill;
 q('efSwap').onclick=()=>{[ep.x,ep.y]=[ep.y,ep.x];ep.mode='auto';render()};q('efReset').onclick=()=>{Object.assign(ep,{x:'sampler_steps',y:'quality_score',split:'none',mode:'auto',metric:'mean',threshold:5});render()};q('efMode').onchange=e=>{ep.mode=e.target.value;efDraw()};document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{ep.metric=b.dataset.metric;render()});document.querySelectorAll('[data-threshold]').forEach(b=>b.onclick=()=>{ep.threshold=+b.dataset.threshold;render()});q('efFilter').onclick=()=>document.body.classList.toggle('ef-filters-open');efDraw()}


/* GBR CORE / NAVIGATION */
'use strict';
const $=id=>document.getElementById(id);const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const average=a=>a.length?a.reduce((s,n)=>s+n,0)/a.length:NaN;const fix=(x,n=2)=>Number.isFinite(x)?x.toFixed(n):'—';const score=r=>r.quality_score==null?NaN:Number(r.quality_score);
const PRIOR_N=20;let evidenceMode='conservative',minimumN=10;
function cohortStats(g){const sample=filtered.map(score).filter(n=>Number.isFinite(n)&&n>=0&&n<=5);const mu=sample.length?average(sample):3;const variance=sample.length>1?Math.max(.25,average(sample.map(x=>(x-mu)**2))):1.5;const sum=g.rows.reduce((a,r)=>a+score(r),0);const estimate=(sum+PRIOR_N*mu)/(g.n+PRIOR_N);const sd=Math.sqrt(variance/(g.n+PRIOR_N));const lb=Math.max(0,estimate-1.96*sd),ub=Math.min(5,estimate+1.96*sd);return {...g,adjusted:estimate,low:lb,high:ub,uncertainty:ub-lb,reliability:g.n/(g.n+PRIOR_N),eligible:g.n>=minimumN}}
function evidence(g){return cohortStats(g)}
function orderGroups(data,mode='score'){return data.map(evidence).sort((a,b)=>{if(evidenceMode==='raw')return mode==='count'?b.n-a.n||b.avg-a.avg:mode==='numeric'?Number(a.name)-Number(b.name):b.avg-a.avg||b.n-a.n;if(mode==='numeric')return Number(a.name)-Number(b.name);if(mode==='count')return b.n-a.n||b.low-a.low;return (b.eligible?1:0)-(a.eligible?1:0)||b.low-a.low||b.n-a.n})}
function evidenceLegend(){return `<div class="evidence-legend"><span>● Thick fill: confidence-adjusted mean</span><span>│ Band: approximate 95% interval</span><span>n below ${minimumN}: exploratory</span><span>Ranked by lower confidence bound</span></div>`}
function meanTooltip(x){return `${x.name}: raw ${fix(x.avg)} / 5 | adjusted ${fix(x.adjusted)} | approx. 95% interval ${fix(x.low)}–${fix(x.high)} | n=${x.n}`}

let rows=[],filtered=[],view='explorer',page=0;let captionFilter='sample';const LIMIT=45;
const labels={explorer:['GBR RESEARCH / EXPLORER','The <i>Experiment Floor.</i>','Choose two properties. Trace a pattern. Pull apart the evidence.'],overview:['THE BIG PICTURE','The sound of <i>discovery.</i>','Every rating is a human decision. Every measurement is a clue.'],parameters:['GENERATION CONTROL','Twist the <i>dials.</i>','Does more guidance, more sampling or a different algorithm actually sound better?'],genres:['SONGS / GENRES / STYLES','A galaxy of <i>sound.</i>','Explore which compositions and musical treatments rise above the noise.'],audio:['FLAC RESEARCH','Under the <i>waveform.</i>','Compare real rhythmic and spectral measurements to your listening scores.'],precision:['COMPUTE RESEARCH','Quality has <i>a cost.</i>','Encoder and DiT precision across pods, with verified cost and quality joins.'],simulator:['PREDICTIVE WORKBENCH','Test the <i>possibilities.</i>','Explore acceptance, failure and uncertainty across generation settings.'],archive:['INDIVIDUAL GENERATIONS','The recording <i>vault.</i>','Every generation, every rating, every parameter. Select a row to inspect its record.']};
function groups(key,rs=filtered){const map=new Map;rs.forEach(r=>{let k=typeof key==='function'?key(r):r[key];k=k==null||k===''?'Unknown':String(k);if(!map.has(k))map.set(k,[]);map.get(k).push(r)});return [...map].map(([name,a])=>({name,n:a.length,avg:average(a.map(score)),good:a.filter(r=>score(r)>=4).length,poor:a.filter(r=>score(r)<=2).length,rows:a}))}
function sampleNote(n){return n<5?'Tiny sample — exploratory only':n<15?'Small sample — interpret cautiously':'Observed association, not a causal effect'}
function panel(title,tag,inside,note='',wide=false){return `<article class="instrument ${wide?'wide':''}"><div class="cap"><h3>${title}</h3><small>${tag}</small></div>${inside}${note?`<p class="subtext">${note}</p>`:''}</article>`}
function section(title,desc){return `<div class="section-prelude"><h2>${title}</h2><p>${desc}</p></div>`}
function barPlot(data,{limit=13,sort='count',showCount=true}={}){let d=orderGroups(data.filter(x=>Number.isFinite(x.avg)),sort).slice(0,limit);if(!d.length)return '<div class="empty">No matching measurements.</div>';return `<div class="evidence-rows">${d.map(x=>{const position=evidenceMode==='raw'?x.avg:x.adjusted;return `<div class="horizontal-bar evidence-row ${x.eligible?'':'tentative'}" title="${safe(meanTooltip(x))}"><span class="name">${safe(x.name)}${!x.eligible?'<small class="low-n">LOW N</small>':''}</span><span class="track"><span class="interval" style="left:${(x.low/5*100).toFixed(1)}%;width:${((x.high-x.low)/5*100).toFixed(1)}%"></span><b style="width:${(position/5*100).toFixed(1)}%"></b><i class="conf-marker" style="left:${(x.low/5*100).toFixed(1)}%"></i></span><span class="number">${fix(position)} <small>n=${x.n}</small>${evidenceMode!=='raw'?`<small class="raw-mean">raw ${fix(x.avg)}</small>`:''}</span></div>`}).join('')}</div>${evidenceLegend()}` }
let plotScale='zoom';
function plotControls(){return `<div class="plot-scale-controls"><div><strong>EXPERIMENT CHART SCALE</strong><small>Zoom emphasises differences; intervals and group sizes remain visible.</small></div><div class="plot-scale-buttons" role="group" aria-label="Experiment graph scale">${[['zoom','ZOOMED'],['full','FULL 0–5'],['delta','Δ FROM MEAN']].map(([id,label])=>`<button type="button" data-plot-scale="${id}" class="${plotScale===id?'active':''}" aria-pressed="${plotScale===id}">${label}</button>`).join('')}</div></div>`}
function linePlot(data){
  const d=orderGroups(data.filter(x=>Number.isFinite(x.avg)),'numeric');
  if(!d.length)return '<div class="empty">No measurements.</div>';
  const W=690,H=282,L=54,R=25,T=30,B=56;
  const baseline=average(filtered.map(score).filter(Number.isFinite));
  const delta=plotScale==='delta',full=plotScale==='full';
  const center=Number.isFinite(baseline)?baseline:2.5;
  const transformed=d.map(x=>{
    const m=evidenceMode==='raw'?x.avg:x.adjusted;
    const offset=delta?center:0;
    return {...x,value:m-offset,lo:x.low-offset,hi:x.high-offset};
  });
  const limits=transformed.flatMap(x=>[x.value,x.lo,x.hi]);
  let min,max;
  if(full){min=0;max=5}
  else{
    let lo=Math.min(...limits),hi=Math.max(...limits);
    if(delta){lo=Math.min(lo,0);hi=Math.max(hi,0)}
    else {lo=Math.min(lo,center);hi=Math.max(hi,center)}
    const spread=Math.max(.12,hi-lo),padding=Math.max(.045,spread*.13);
    min=Math.floor((lo-padding)*20)/20;
    max=Math.ceil((hi+padding)*20)/20;
    if(!delta){min=Math.max(0,min);max=Math.min(5,max)}
    if(max-min<.2){const mid=(max+min)/2;min=mid-.1;max=mid+.1}
  }
  const xx=i=>L+i*(W-L-R)/Math.max(d.length-1,1);
  const yy=v=>T+(max-v)/(max-min)*(H-T-B);
  const ticks=Array.from({length:5},(_,i)=>min+(max-min)*i/4);
  const axis=full?'Full rating scale 0–5':delta?'Difference from filtered mean':'Zoomed rating scale';
  const line=transformed.map((x,i)=>`${xx(i)},${yy(x.value)}`).join(' ');
  const clamp=v=>Math.max(T,Math.min(H-B,yy(v)));
  const base=delta?0:center;
  const guide=base>=min&&base<=max?`<line class="plot-baseline" x1="${L}" x2="${W-R}" y1="${yy(base)}" y2="${yy(base)}"/><text x="${W-R-2}" y="${yy(base)-6}" text-anchor="end" class="reference-label">${delta?'ZERO / AVERAGE':'FILTERED MEAN'}</text>`:'';
  const grid=ticks.map(n=>`<line class="grid" x1="${L}" x2="${W-R}" y1="${yy(n)}" y2="${yy(n)}"/><text x="7" y="${yy(n)+4}">${delta?(n>0?'+':'')+fix(n,2):fix(n,2)}</text>`).join('');
  return `<div class="plot"><div class="plot-range-note">${axis}: <b>${fix(min,2)} to ${fix(max,2)}</b> · filtered mean ${fix(center,2)}/5</div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${axis}. Confidence-adjusted scores, approximate intervals and sample counts.">${grid}${guide}<line class="axis" x1="${L}" x2="${W-R}" y1="${H-B}" y2="${H-B}"/>${transformed.map((x,i)=>`<line class="confidence-whisker ${x.eligible?'':'low-evidence'}" x1="${xx(i)}" x2="${xx(i)}" y1="${clamp(x.hi)}" y2="${clamp(x.lo)}"/><line class="confidence-whisker ${x.eligible?'':'low-evidence'}" x1="${xx(i)-6}" x2="${xx(i)+6}" y1="${clamp(x.lo)}" y2="${clamp(x.lo)}"/><line class="confidence-whisker ${x.eligible?'':'low-evidence'}" x1="${xx(i)-6}" x2="${xx(i)+6}" y1="${clamp(x.hi)}" y2="${clamp(x.hi)}"/>`).join('')}<polyline fill="none" stroke="#d6ad62" stroke-width="2.5" points="${line}"/>${transformed.map((x,i)=>`<circle class="dot ${x.eligible?'':'low-evidence'}" cx="${xx(i)}" cy="${yy(x.value)}" r="${Math.max(4,Math.min(10,3+Math.sqrt(x.n)/2))}" fill="${x.eligible?'#e9b865':'#9a8980'}"><title>${safe(meanTooltip(x))}${delta?' | delta '+fix(x.value,3):''}</title></circle><text x="${xx(i)}" y="${H-22}" text-anchor="middle">${safe(x.name)}</text><text class="sample-count" x="${xx(i)}" y="${H-6}" text-anchor="middle">n=${x.n}</text>`).join('')}</svg></div>${evidenceLegend()}`;
}
function scatter(key,label){const d=filtered.filter(r=>r[key]!=null&&Number.isFinite(+r[key]));if(!d.length)return '<div class="empty">No audio measurements in this selection.</div>';const W=690,H=290,L=55,R=23,T=22,B=48,vals=d.map(r=>+r[key]),min=Math.min(...vals),max=Math.max(...vals),delta=max-min||1;let dots=d.map((r,i)=>{const x=L+((+r[key]-min)/delta)*(W-L-R),y=T+((5-score(r))/4)*(H-T-B),color=['','#a86e67','#ac875d','#c7b777','#a5c090','#e1b968'][score(r)];return `<circle class="dot" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="3.7" opacity=".69" fill="${color}"><title>${safe(r.title||r.audio_file)} · ${fix(+r[key])} · grade ${score(r)}</title></circle>`}).join('');return `<div class="plot"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${safe(label)} versus listening grade">${[1,2,3,4,5].map(n=>{const y=T+(5-n)/4*(H-T-B);return `<line class="grid" x1="${L}" x2="${W-R}" y1="${y}" y2="${y}"/><text x="10" y="${y+4}">${n} / 5</text>`}).join('')}<line class="axis" x1="${L}" x2="${W-R}" y1="${H-B}" y2="${H-B}"/><text x="${L}" y="${H-16}">${fix(min,1)}</text><text x="${W-R}" y="${H-16}" text-anchor="end">${fix(max,1)}</text>${dots}</svg></div><p class="subtext">${d.length} real FLAC profiles. X axis: ${safe(label)}. Y axis: human rating. Hover any point for the recording name.</p>`}
function overview(){const counts=[0,1,2,3,4,5].map(s=>filtered.filter(r=>score(r)===s).length),total=filtered.length,good=filtered.filter(r=>score(r)>=4).length,bad=filtered.filter(r=>score(r)<=2).length;const strip=`<div class="rating-strip">${counts.map((n,i)=>`<span class="grade${i}" style="flex:${n||.05}" title="Grade ${i}: ${n} recordings"></span>`).join('')}</div><div class="grade-legend">${counts.map((n,i)=>`<span><i class="legend-chip grade${i}"></i>${i===0?"0 / Unlistenable":i+"/5"} · ${n}</span>`).join('')}</div>`;return section('A studio full of experiments','Your ratings are the ground truth. Charts show associations in this specific collection, not guarantees of better output.')+`<div class="grid-two">${panel('What made the cut?','THE QUALITY MIX',`<div class="big-ratio">${total?fix(100*good/total,1):'—'}%</div><p class="subtext">Scored 4 or 5: ${good} of ${total} attempts. ${bad} were rated 0–2.</p>${strip}<div class="finding">The archive is deliberately selective. A high failure rate is useful information when testing unfamiliar genres and extreme settings.</div>`)}${panel('Generations by genre','MEAN HUMAN SCORE',barPlot(groups('cluster'),{limit:10}),'Cluster means can be influenced by the particular songs and settings sampled.')}${panel('Encoder guidance','CFG / QUALITY RESPONSE',linePlot(groups('encoder_cfg')),'Hover the points for group sizes.')}${panel('Sampler / scheduler','COMPARATIVE RATINGS',barPlot(groups(r=>[r.sampler,r.scheduler].filter(Boolean).join(' / ')),{limit:8}),'Sampler and scheduler are often paired, so this chart does not isolate their individual effects.')}</div>`}
function heat(){const rs=filtered.filter(r=>r.sampler&&r.scheduler);const sam=[...new Set(rs.map(r=>r.sampler))].sort(),sch=[...new Set(rs.map(r=>r.scheduler))].sort();if(!sam.length)return '<div class="empty">No algorithms recorded.</div>';const cell=(a,b)=>{const x=rs.filter(r=>r.sampler===a&&r.scheduler===b);if(!x.length)return '<td>—</td>';const g=evidence({name:`${a} / ${b}`,n:x.length,avg:average(x.map(score)),rows:x});const shown=evidenceMode==='raw'?g.avg:g.adjusted;const alpha=g.eligible?(.09+(shown-1)/4*.55).toFixed(2):.06;return `<td class="${g.eligible?'':'tentative'}" style="background:rgba(229,177,88,${alpha})" title="${safe(meanTooltip(g))}">${fix(shown)}<br><small>n=${g.n}${!g.eligible?' · LOW N':''}</small></td>`};return `<div class="plot"><table class="heat-table"><thead><tr><th>SAMPLER ↓ / SCHEDULER →</th>${sch.map(s=>`<th>${safe(s)}</th>`).join('')}</tr></thead><tbody>${sam.map(a=>`<tr><th>${safe(a)}</th>${sch.map(b=>cell(a,b)).join('')}</tr>`).join('')}</tbody></table></div>${evidenceLegend()}` }
function parameters(){return section('The experiment board','Each dial changes a different part of generation. Find stable regions, not just one lucky maximum.')+plotControls()+`<div class="grid-two">${panel('Encoder CFG','GUIDANCE RESPONSE',linePlot(groups('encoder_cfg')))}${panel('Sampling steps','ITERATION RESPONSE',linePlot(groups('sampler_steps')))}${panel('Top-k','CONDITIONING DIVERSITY',linePlot(groups('top_k')))}${panel('Sampler CFG','DIFFUSION GUIDANCE',linePlot(groups('sampler_cfg')))}${panel('The pairing matrix','ALGORITHM × SCHEDULE',heat(),'Blank cells represent combinations that were not tested.',true)}${panel('Caption length','WORD COUNT',barPlot(binned('caption_words'),{limit:9,sort:'numeric'}))}${panel('Lyrics length','WORD COUNT',barPlot(binned('lyrics_words'),{limit:9,sort:'numeric'}))}</div>`}
function binned(field,n=7){const a=filtered.filter(r=>r[field]!=null&&Number.isFinite(+r[field]));if(!a.length)return [];const vals=a.map(r=>+r[field]),lo=Math.min(...vals),hi=Math.max(...vals),step=(hi-lo||1)/n;return groups(r=>r[field]==null?'Unknown':`${Math.floor((+r[field]-lo)/step)<n?Math.floor((+r[field]-lo)/step):n-1}`).filter(x=>x.name!=='Unknown').map(x=>{const i=+x.name;return {...x,name:`${fix(lo+i*step,0)}–${fix(lo+(i+1)*step,0)}`}})}
function genres(){const songs=orderGroups(groups('title').filter(g=>g.name!=='Unknown'),'count'),clusters=groups('cluster').filter(g=>g.name!=='Unknown');const starfield=songs.filter(s=>s.n>=3).slice(0,70);const W=840,H=440;const dots=starfield.map((s,i)=>{const phi=i*2.399963,x=W/2+Math.cos(phi)*Math.sqrt(i/Math.max(1,starfield.length))*W*.45,y=H/2+Math.sin(phi)*Math.sqrt(i/Math.max(1,starfield.length))*H*.43,r=5+Math.sqrt(s.n)*3.3,colors=['#af6d62','#bb8762','#cdb674','#97b995','#e6bd64'];const rating=evidenceMode==='raw'?s.avg:s.adjusted;return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(1)}" fill="${s.eligible?colors[Math.max(0,Math.min(4,Math.round(rating)-1))]:'#80796d'}" opacity="${s.eligible?'.85':'.38'}" class="song-star" data-song="${safe(s.name)}"><title>${safe(meanTooltip(s))}</title></circle>`}).join('');return section('Your musical universe','Star size reflects review count; colour indicates adjusted evidence, not a single lucky score. Grey stars have thin evidence.')+`<div class="grid-two">${panel('Composition constellation','INTERACTIVE MAP',`<div class="plot"><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Click song stars to filter by composition" style="background:radial-gradient(ellipse at center,#3a342450,transparent 67%)"><circle cx="420" cy="220" r="120" fill="none" stroke="#ffffff0d"/><circle cx="420" cy="220" r="200" fill="none" stroke="#ffffff0d"/>${dots}</svg></div>${evidenceLegend()}`,`Grey or transparent stars are exploratory (n under ${minimumN}).`,true)}${panel('Highest-evidence clusters',`RANKED BY LOWER 95% BOUND · MIN ${minimumN}`,barPlot(clusters,{sort:'score',limit:12}))}${panel('Most tested compositions','RATING / ATTEMPTS',barPlot(songs,{limit:14}))}</div>`}
function audio(){const count=filtered.filter(r=>r.duration!=null).length;return section('Dissecting the signal',`${count} of ${filtered.length} selected generations include measured FLAC audio characteristics. These are descriptive audio measurements, NOT assessments of human realism, voice quality or musical correctness. Tempo can be misread at half/double speed.`)+`<div class="finding"><strong>How to read this page</strong><p>Each dot is one measured generation. Horizontal position is the physical audio feature and vertical position is your human quality rating. A cloud of dots with no upward/downward tendency means the measurement alone does not predict quality. High energy = stronger signal intensity; onset density = detected attacks per second; brightness = relative high-frequency content; bass = low-frequency content. All depend strongly on genre and arrangement.</p><p>Use the GENRE CLUSTER and CAPTION SOURCE filters above to compare comparable tracks. These plots cannot independently identify correct instruments, literal human-sounding vocals or whether the requested musical style was achieved.</p></div>`+`<div class="grid-two">${panel('Tempo versus quality','BPM',scatter('bpm','Estimated BPM'),'Look for tendencies, not one universal ideal tempo.',true)}${panel('Energy variability','DYNAMICS',scatter('energy_std','Energy standard deviation'))}${panel('Rhythmic density','ONSETS / SECOND',scatter('onset_density','Onset density'))}${panel('Spectral brightness','FREQUENCY BALANCE',scatter('brightness_mean','Average brightness'))}${panel('Bass energy','LOW FREQUENCY CONTENT',scatter('bass_mean','Bass activity'))}${panel('RMS loudness','AVERAGE LEVEL DB',scatter('rms_db','RMS dB'))}${panel('Peak level','PEAK DB',scatter('peak_db','Peak level in dB'))}</div>`}
let costDataset=null;
function costMoney(n){return Number.isFinite(n)?'$'+n.toFixed(n<.1?4:2):'—'}
function computeCost(){
 if(!costDataset)return panel('Cost telemetry','NOT IMPORTED',`<div class="empty">Pipeline cost data is not yet imported. Supply generation_timings.csv to the analytics refresh launcher. No estimated prices are substituted.</div>`,'Pipeline data is independent of FLAC profiling.',true);
 const d=costDataset;const selection=new Set(filtered.map(x=>x.id));const linked=(d.matched_generations||[]).filter(x=>selection.has(x.generation_id));const reviewed=linked.filter(x=>x.quality_score!=null&&x.stages&&x.stages.includes('conditioning_total')&&x.stages.includes('sampling_total'));const accepted=reviewed.filter(x=>Number(x.quality_score)>=4);const rejected=reviewed.filter(x=>Number(x.quality_score)===0);const priced=reviewed.reduce((v,x)=>v+Number(x.cost_usd||0),0);
 const overall=panel('Cost / benefit register','MATCHED REVIEWED GENERATIONS',`<div class="cost-stat-grid"><div><small>MATCHED REVIEWS</small><strong>${reviewed.length}</strong></div><div><small>COST PER REVIEWED ATTEMPT</small><strong>${reviewed.length?costMoney(priced/reviewed.length):'—'}</strong></div><div><small>COST PER ACCEPTED (4–5)</small><strong>${accepted.length?costMoney(priced/accepted.length):'—'}</strong></div><div><small>UNLISTENABLE / 0</small><strong>${rejected.length}</strong></div></div><p class="subtext">These estimates include the cost of rejected attempts and only count generations with both conditioning and sampling stage totals in the matched reviewed cohort. They exclude unrated attempts and cannot be treated as total pipeline cost. Source matched ${d.matched_count} unique generations out of ${d.source_rows} timing rows.</p>`, '',true);
 const ws=d.workers||[];
 const workerPanel=panel('Pod cost ledger','PIPELINE BILLABLE STAGES',`<div class="plot"><table class="vault-table"><thead><tr><th>POD</th><th>GPU</th><th>EST. SPEND</th><th>BILLABLE ROWS</th><th>WORKER HOURS</th></tr></thead><tbody>${ws.map(x=>`<tr><td><strong>${safe(x.worker)}</strong></td><td>${safe(x.gpu)}</td><td>${costMoney(+x.cost_usd)}</td><td>${x.billable_rows}</td><td>${fix(+x.worker_seconds/3600,2)}</td></tr>`).join('')}</tbody></table></div>`,'Stage totals are costed; nonbillable sub-stages are not added a second time.',true);
 const map=new Map();for(const x of reviewed){const key=`${x.text_encoder||'Unknown'} / ${x.dit||'Unknown'}`;if(!map.has(key))map.set(key,[]);map.get(key).push(x)}
 const efficiency=[...map].map(([key,x])=>{const successes=x.filter(r=>+r.quality_score>=4);const cost=x.reduce((v,r)=>v+(+r.cost_usd||0),0);return {key,n:x.length,success:successes.length,rate:successes.length/x.length,cost,per:successes.length?cost/successes.length:null}}).sort((a,b)=>(a.per??Infinity)-(b.per??Infinity));
 const efficiencyPanel=panel('Precision value','ENCODER / DiT',`<div class="plot"><table class="vault-table"><thead><tr><th>ENC / DiT</th><th>REVIEWED</th><th>4–5</th><th>SUCCESS %</th><th>EST. $ / ACCEPTED</th></tr></thead><tbody>${efficiency.map(x=>`<tr><td><strong>${safe(x.key)}</strong></td><td>${x.n}${x.n<minimumN?' · LOW N':''}</td><td>${x.success}</td><td>${fix(x.rate*100,1)}%</td><td>${x.n<minimumN?'Exploratory · ':''}${x.per!=null?costMoney(x.per):'No accepts'}</td></tr>`).join('')}</tbody></table></div>`,'Raw success rates and costs are exploratory at small sample sizes; matched generations only.',true);
 const audit=panel('Match integrity','NO ASSUMED COST ASSIGNMENTS',`<div class="cost-stat-grid"><div><small>UNMATCHED BILLABLE ROWS</small><strong>${d.unmatched_rows}</strong></div><div><small>AMBIGUOUS PATHS</small><strong>${d.ambiguous_rows}</strong></div><div><small>SKIPPED / NONBILLABLE</small><strong>${d.skipped_rows}</strong></div><div><small>VERIFIED LINKS</small><strong>${d.matched_count}</strong></div></div><p class="subtext">If the match count is low, add stable generation IDs or exact FLAC names to the runner telemetry. Pod spend is shown separately from quality until identities match.</p>`,d.warning||'',true);
 return overall+`<div class="grid-two">${workerPanel}${efficiencyPanel}${audit}</div>`;
}
function precision(){const combos=groups(r=>`${r.text_encoder||'Unknown'} encoder / ${r.dit||'Unknown'} DiT`);return section('The compute tradeoff',`Only ${combos.filter(x=>x.n>=minimumN).length} precision cohorts meet the selected sample threshold of ${minimumN}. Small new precision batches are exploratory, not winners.`)+`<div class="grid-two">${panel('Precision experiments','EVIDENCE-AWARE COMPARISON',barPlot(combos,{sort:'score',limit:20}),'Ranking uses a conservative lower confidence bound, with a cohort-size threshold.')}${panel('Coverage matrix','ACTUAL OBSERVATIONS',`<div class="finding">${orderGroups(combos,'score').map(c=>`${safe(c.name)} — n=${c.n}; raw ${fix(c.avg)}; adjusted ${fix(c.adjusted)}; interval ${fix(c.low)}–${fix(c.high)} ${c.eligible?'':'[EXPLORATORY]'}`).join('<br>')}</div>`,'Pod hardware and song mixture can still confound comparisons.')}</div>`+section('Efficiency laboratory','Cost totals are linked to actual telemetry records. No guessed pod-to-audio relationships.')+computeCost()}
function archive(){const a=filtered.slice(page*LIMIT,(page+1)*LIMIT);return section('The complete experiment log','Choose a recording to inspect its exact YAML values and acoustic profile.')+`<div class="instrument"><div class="archive-controls"><span>SHOWING ${filtered.length?1+page*LIMIT:0}–${Math.min((page+1)*LIMIT,filtered.length)} / ${filtered.length} GENERATIONS</span><div><button id="prev" ${page===0?'disabled':''}>← PREV</button> <button id="next" ${(page+1)*LIMIT>=filtered.length?'disabled':''}>NEXT →</button></div></div><div class="plot"><table class="vault-table"><thead><tr><th>COMPOSITION</th><th>STYLE / VERSION</th><th>CLUSTER</th><th>GRADE</th><th>AUDIO</th><th>ENC / DiT</th></tr></thead><tbody>${a.map(r=>`<tr data-record="${safe(r.id)}"><td><strong>${safe(r.title||r.audio_file||'Unidentified')}</strong></td><td>${safe(r.version||'—')}</td><td>${safe(r.cluster||'—')}</td><td><span class="score grade${score(r)}">${score(r)}</span></td><td><span class="chip">${r.duration!=null?'PROFILED':'MISSING'}</span></td><td>${safe(r.text_encoder||'?')} / ${safe(r.dit||'?')}</td></tr>`).join('')}</tbody></table></div></div>`}
function detail(id){const r=rows.find(x=>x.id===id);if(!r)return;const fields=[['LISTENING GRADE',`${score(r)} / 5`],['GENRE CLUSTER',r.cluster],['GENRE VERSION',r.version],['MODEL',r.model],['ENCODER PRECISION',r.text_encoder],['DiT PRECISION',r.dit],['ENCODER CFG',r.encoder_cfg],['SAMPLER CFG',r.sampler_cfg],['TOP K',r.top_k],['SAMPLER STEPS',r.sampler_steps],['SAMPLER',r.sampler],['SCHEDULER',r.scheduler],['ENCODER SEED',r.encoder_seed],['SAMPLER SEED',r.sampler_seed],['LENGTH / SEC',r.duration],['TEMPO / BPM',r.bpm],['RMS / DB',r.rms_db],['PEAK / DB',r.peak_db],['ONSET DENSITY',r.onset_density],['ENERGY VARIATION',r.energy_std],['BASS ENERGY',r.bass_mean],['BRIGHTNESS',r.brightness_mean],['CAPTION WORDS',r.caption_words],['LYRIC WORDS',r.lyrics_words],['YAML FILE',r.yaml_file],['AUDIO FILE',r.audio_file],['CATALOGUE',r.published?'Matched to GBR':'Research / unmatched']];$('drawerId').textContent=String(r.id).slice(0,9);$('drawerBody').innerHTML=`<div class="eyebrow" style="margin-top:27px">ORIGINAL EXPERIMENT RECORD</div><h2>${safe(r.title||r.audio_file||'Unidentified recording')}</h2><p style="color:#b5a48a">${safe(r.version||r.cluster||'Unclassified')}</p><div class="drawer-grid">${fields.map(([label,value])=>`<div class="drawer-field"><small>${safe(label)}</small><strong>${safe(value??'—')}</strong></div>`).join('')}</div>`;$('scrim').hidden=false;$('drawer').classList.add('open');$('drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('scrim').hidden=true;$('drawer').classList.remove('open');$('drawer').setAttribute('aria-hidden','true')}
function render(){document.body.classList.toggle('explorer-active',view==='explorer');const [k,h,sub]=labels[view];$('kicker').textContent=k;$('headline').innerHTML=h;$('subtitle').textContent=sub;const good=filtered.filter(r=>score(r)>=4).length,profile=filtered.filter(r=>r.duration!=null).length,mean=average(filtered.map(score));$('metrics').innerHTML=[['GENERATIONS',filtered.length.toLocaleString(),'RATED ATTEMPTS'],['MEAN LISTENING SCORE',fix(mean),'OUT OF FIVE'],['KEPT / 4–5',filtered.length?fix(good/filtered.length*100,1)+'%':'—',`${good} HIGH SCORERS`],['AUDIO PROFILES',profile.toLocaleString(),`${filtered.length?fix(profile/filtered.length*100,1):'0'}% OF SELECTION`]].map(([a,b,c])=>`<div class="meter"><small>${a}</small><strong>${b}</strong><em>${c}</em></div>`).join('');$('viewContent').innerHTML=({explorer:explorerView,overview,parameters,genres,audio,precision,archive,simulator:simulatorView})[view]();document.querySelectorAll('#nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-plot-scale]').forEach(b=>b.addEventListener('click',()=>{plotScale=b.dataset.plotScale;render()}));document.querySelectorAll('[data-record]').forEach(tr=>tr.addEventListener('click',()=>detail(tr.dataset.record)));document.querySelectorAll('.song-star').forEach(el=>{el.style.cursor='pointer';el.addEventListener('click',()=>{$('song').value=el.dataset.song;apply();})});if(view==='simulator')wireSimulator();if(view==='explorer')wireExplorer();if($('prev'))$('prev').onclick=()=>{page--;render()};if($('next'))$('next').onclick=()=>{page++;render()}}
function apply(){const s=$('search').value.toLowerCase().trim(),song=$('song').value,cluster=$('cluster').value,grade=$('grade').value,caption=$('captionSource').value;filtered=rows.filter(r=>(!caption||(caption==='missing'?!r.caption_source:r.caption_source===caption))&&(!song||r.title===song)&&(!cluster||r.cluster===cluster)&&(!grade||String(score(r))===grade)&&(!s||[r.title,r.cluster,r.version,r.audio_file,r.sampler,r.scheduler].some(v=>String(v||'').toLowerCase().includes(s))));page=0;render()}
function fillOptions(){for(const [id,key] of [['song','title'],['cluster','cluster']]){const el=$(id),vals=[...new Set(rows.map(r=>r[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b));vals.forEach(v=>{const option=document.createElement('option');option.value=v;option.textContent=v;el.appendChild(option)})}}
async function boot(){const form=document.querySelector('.filter-grid');if(form){const wrapper=document.createElement('div');wrapper.className='evidence-controls';wrapper.innerHTML='<label>EVIDENCE VIEW<select id="evidenceMode"><option value="conservative">Evidence adjusted (recommended)</option><option value="raw">Raw means (exploratory)</option></select></label><label>MINIMUM SAMPLES<select id="minimumN"><option value="5">5</option><option value="10" selected>10</option><option value="20">20</option><option value="50">50</option></select></label>';form.parentNode.insertBefore(wrapper,form.nextSibling);$('evidenceMode').onchange=e=>{evidenceMode=e.target.value;render()};$('minimumN').onchange=e=>{minimumN=+e.target.value;render()}}document.querySelectorAll('#nav [data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;page=0;render();if(innerWidth<700)window.scrollTo({top:0,behavior:'smooth'})});for(const id of ['search','song','cluster','captionSource','grade'])$(id).addEventListener(id==='search'?'input':'change',apply);$('reset').onclick=()=>{for(const id of ['search','song','cluster','captionSource','grade'])$(id).value='';apply()};$('closeDrawer').onclick=closeDrawer;$('scrim').onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});try{const response=await fetch('../data/analytics/generations.json',{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();if(!Array.isArray(data.generations))throw Error('Invalid dataset');rows=data.generations;filtered=rows.slice();fillOptions();$('dataStamp').textContent='DATA / '+new Date(data.generated_at).toLocaleDateString('en-GB');$('sideCount').textContent=rows.length+' RECORDINGS';try{const costResponse=await fetch('../data/analytics/cost-analysis.json',{cache:'no-store'});if(costResponse.ok){const cost=await costResponse.json();if(cost.format==='gbr-compute-cost-v1')costDataset=cost}}catch(error){console.info('Optional cost telemetry absent:',error)}render()}catch(e){$('viewContent').innerHTML=`<div class="notice">RESEARCH SIGNAL UNAVAILABLE: ${safe(e.message)}. Refresh analytics and serve the built site over HTTP.</div>`;$('dataStamp').textContent='NO DATA';console.error(e)}}boot();

// GBR Generation Simulator: similarity-weighted empirical estimates, not a causal model.
const SIM_KEYS=[['encoder_cfg','Encoder CFG'],['sampler_cfg','Sampler CFG'],['top_k','Top-k'],['sampler_steps','Sampler steps']];
const SIM_RANGES={encoder_cfg:[1,2,.1],sampler_cfg:[1,2,.1],top_k:[10,200,5],sampler_steps:[10,100,5]};
const simState={compare:'none',encoder_cfg:1.6,sampler_cfg:1.6,top_k:45,sampler_steps:35,text_encoder:'bf16',dit:'fp32',pair:'dpmpp_sde_gpu / ddim_uniform',axis:'encoder_cfg',outcome:'accepted'};
const simFinite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
function simPool(){return filtered.filter(r=>Number.isFinite(score(r))&&score(r)>=0&&score(r)<=5&&(captionFilter==='all'||r.caption_source===captionFilter))}
function simChoices(field){return [...new Set(rows.map(r=>r[field]).filter(v=>v!=null&&String(v).trim()).map(String))].sort()}
function simPairs(){return [...new Set(rows.filter(r=>r.sampler&&r.scheduler).map(r=>r.sampler+' / '+r.scheduler))].sort()}
function simEst(at,rs=simPool()){
 const usable=rs.filter(r=>SIM_KEYS.every(([k])=>simFinite(r[k]))&&r.text_encoder&&r.dit&&r.sampler&&r.scheduler);
 const exact=usable.filter(r=>String(r.text_encoder)===at.text_encoder&&String(r.dit)===at.dit&&r.sampler+' / '+r.scheduler===at.pair);
 // Strictly respect categorical settings. Zero matching cohort -> no unsupported predictions.
 if(!exact.length)return {available:false,n:0,reason:'No reviewed recordings for this exact encoder / DiT / sampler pairing.'};
 let sum=0,sumSq=0,success=0,zero=0,quality=0,neighbors=0;
 const ranges={encoder_cfg:.22,sampler_cfg:.22,top_k:38,sampler_steps:23};
 for(const r of exact){let d2=0;for(const [k] of SIM_KEYS){const d=(Number(r[k])-Number(at[k]))/ranges[k];d2+=d*d}const w=Math.exp(-.5*d2);if(w<1e-5)continue;sum+=w;sumSq+=w*w;success+=w*(score(r)>=4?1:0);zero+=w*(score(r)===0?1:0);quality+=w*score(r);neighbors++}
 if(sum<.001)return {available:false,n:exact.length,reason:'The selected numeric settings are too far from reviewed observations.'};
 // Kish effective n, penalise low absolute kernel weight as well: far-away cohorts remain uncertain.
 const kish=sum*sum/sumSq;const eff=Math.min(kish,sum);const base=rs.filter(r=>Number.isFinite(score(r)));const priorP=base.filter(r=>score(r)>=4).length/base.length;
 const priorZ=base.filter(r=>score(r)===0).length/base.length;
 const k=12;const p=(success+k*priorP)/(sum+k);const z=(zero+k*priorZ)/(sum+k);
 const pWidth=1.96*Math.sqrt(Math.max(.00001,p*(1-p))/(eff+k));
 const zWidth=1.96*Math.sqrt(Math.max(.00001,z*(1-z))/(eff+k));
 const proximity=Math.min(1,eff/12); // widen when very few near samples
 const penalty=.22*(1-proximity);
 const bounds=(v,w)=>[Math.max(0,v-w-penalty),Math.min(1,v+w+penalty)];
 return {available:true,p,z,pl:bounds(p,pWidth)[0],ph:bounds(p,pWidth)[1],zl:bounds(z,zWidth)[0],zh:bounds(z,zWidth)[1],q:(quality+k*average(base.map(score)))/(sum+k),eff,n:exact.length,neighbors,raw:success/sum,weight:sum,sparse:eff<minimumN};
}
function simulatorView(){
 const pool=simPool();if(!pool.length)return section('Generation simulator','No rated recordings are available.');
 const select=(id,values,value)=>`<label>${id}<select data-sim="${id}" aria-label="${id}">${values.map(x=>`<option value="${safe(x)}" ${String(x)===String(value)?'selected':''}>${safe(x)}</option>`).join('')}</select></label>`;
 const field=(k,label)=>{const [lo,hi,step]=SIM_RANGES[k];return `<label>${label}<div class="sim-dial"><input type="range" data-sim="${k}" min="${lo}" max="${hi}" step="${step}" value="${simState[k]}"><input type="number" data-sim="${k}" min="${lo}" max="${hi}" step="${step}" value="${simState[k]}"></div></label>`};
 return section('The Generation Simulator','Set the controls, explore one parameter across its range, and examine acceptance probabilities with uncertainty. Empirical similarity analysis, not a causal prediction.')+`<div class="sim-controls instrument"><div class="cap"><h3>Set the signal path</h3><small>EXPERIMENT CONFIGURATION</small></div><div class="sim-grid">${SIM_KEYS.map(([k,label])=>field(k,label)).join('')}${select('text_encoder',simChoices('text_encoder'),simState.text_encoder)}${select('dit',simChoices('dit'),simState.dit)}${select('pair',simPairs(),simState.pair)}</div><div class="sim-actions"><button type="button" id="simReset">RESET TO BASELINE</button><small>Dropdown options come from observed model/sampler metadata.</small></div></div><div class="sim-view instrument"><div class="cap"><h3>Acceptance response</h3><small>RESEARCH SCOPE · ${pool.length} RATED</small></div><div class="sim-grid">${select('axis',SIM_KEYS.map(x=>x[0]),simState.axis)}${select('outcome',['accepted','zero','quality'],simState.outcome)}${select('caption_scope',['sample','custom','all'],captionFilter)}${select('compare',['none',...simPairs()],simState.compare)}</div><p class="subtext">Comparison overlay: choose a second sampler / scheduler combination; both curves share the same axis, model settings and outcome. Caption scope defaults to sample.</p><div id="simResults"></div></div>`;
}
function simChart(){const [lo,hi,step]=SIM_RANGES[simState.axis];const points=[];for(let v=lo;v<=hi+step/100;v+=step){let at={...simState,[simState.axis]:+v.toFixed(3)};points.push({x:+v.toFixed(3),e:simEst(at)})}const active=simEst(simState);const W=760,H=310,L=58,R=26,T=25,B=55;const isQuality=simState.outcome==='quality';const X=x=>L+(x-lo)/(hi-lo)*(W-L-R),Y=y=>T+(1-y/(isQuality?5:1))*(H-T-B);const val=e=>isQuality?e.q:simState.outcome==='zero'?e.z:e.p,low=e=>isQuality?Math.max(0,e.q-(e.ph-e.pl)*5):simState.outcome==='zero'?e.zl:e.pl,high=e=>isQuality?Math.min(5,e.q+(e.ph-e.pl)*5):simState.outcome==='zero'?e.zh:e.ph;
 const valid=points.filter(p=>p.e.available);let path='',band='';for(let i=0;i<valid.length;i++){const p=valid[i];path+=(i?'L':'M')+X(p.x).toFixed(2)+' '+Y(val(p.e)).toFixed(2)+' ';}if(valid.length){band=valid.map((p,i)=>(i?'L':'M')+X(p.x).toFixed(2)+' '+Y(high(p.e)).toFixed(2)).join(' ')+' '+valid.slice().reverse().map(p=>'L'+X(p.x).toFixed(2)+' '+Y(low(p.e)).toFixed(2)).join(' ')+'Z'}
 const dots=valid.map(p=>`<circle cx="${X(p.x)}" cy="${Y(val(p.e))}" r="${p.e.sparse?3:5}" fill="${p.e.sparse?'#8d7d61':'#e8c07b'}"><title>${safe(simState.axis)} ${p.x}: ${isQuality?val(p.e).toFixed(2):Math.round(100*val(p.e))+'%'}; approximate interval ${isQuality?low(p.e).toFixed(2):Math.round(100*low(p.e))+'%'}–${isQuality?high(p.e).toFixed(2):Math.round(100*high(p.e))+'%'}; effective n=${p.e.eff.toFixed(1)}; categorical cohort n=${p.e.n}</title></circle>`).join('');
 const labels=Array.from({length:5},(_,i)=>{const n=i/4*(isQuality?5:1);return `<line x1="${L}" x2="${W-R}" y1="${Y(n)}" y2="${Y(n)}" stroke="currentColor" opacity=".12"/><text x="${L-10}" y="${Y(n)+4}" text-anchor="end" fill="currentColor" opacity=".7" font-size="11">${isQuality?n.toFixed(1):Math.round(n*100)+'%'}</text>`}).join('');
 const ticks=Array.from({length:5},(_,i)=>{let x=lo+i*(hi-lo)/4;return `<text x="${X(x)}" y="${H-24}" fill="currentColor" opacity=".7" text-anchor="middle" font-size="11">${+x.toFixed(2)}</text>`}).join('');
 const data=active.available?`<div class="sim-numbers"><div><small>4–5 ACCEPTED</small><strong>${(100*active.p).toFixed(1)}%</strong><small>${(100*active.pl).toFixed(0)}–${(100*active.ph).toFixed(0)}% interval</small></div><div><small>0 / UNLISTENABLE</small><strong>${(100*active.z).toFixed(1)}%</strong><small>${(100*active.zl).toFixed(0)}–${(100*active.zh).toFixed(0)}% interval</small></div><div><small>EXPECTED SCORE</small><strong>${active.q.toFixed(2)} / 5</strong><small>Prior-adjusted</small></div><div><small>EVIDENCE</small><strong>${active.eff.toFixed(1)}</strong><small>effective n · ${active.n} categorical matches</small></div></div><p class="sim-warning">${active.sparse?'LOW EVIDENCE — These estimates are exploratory.':'LOCAL EVIDENCE — Associations can be confounded by song, genre and experiment design.'} Approximate intervals are deliberately widened for sparse evidence; they are not calibrated predictive guarantees.</p>`:`<div class="sim-warning">NO SUPPORTED ESTIMATE — ${safe(active.reason)} ${active.n} categorical matches.</div>`;
 const comparePoints=simState.compare==='none'?[]:points.map(p=>({x:p.x,e:simEst({...simState,[simState.axis]:p.x,pair:simState.compare})})).filter(p=>p.e.available); const comparePath=comparePoints.map((p,i)=>(i?'L':'M')+X(p.x).toFixed(2)+' '+Y(val(p.e)).toFixed(2)).join(' ');
 return `<div class="sim-chart"><div class="subtext">PRIMARY: ${safe(simState.pair)} · COMPARISON: ${safe(simState.compare)} · N = number of matching observations</div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Estimated outcome over ${safe(simState.axis)} with uncertainty boundaries">${labels}${ticks}<path d="${band}" fill="rgba(226,177,89,.20)"/><path d="${path}" fill="none" stroke="#dfb66a" stroke-width="3"/><path d="${comparePath}" fill="none" stroke="#66c1df" stroke-width="3" stroke-dasharray="6 4"/>${dots}<line x1="${X(simState[simState.axis])}" x2="${X(simState[simState.axis])}" y1="${T}" y2="${H-B}" stroke="#f0d9a7" stroke-dasharray="4 5"/><text x="${L}" y="${H-5}" fill="currentColor" font-size="11">${safe(SIM_KEYS.find(x=>x[0]===simState.axis)[1])} →</text></svg></div>${data}<p class="subtext">Shaded: approximate uncertainty. Dashed: selected value. The curve holds all other settings fixed; options with zero matching precision/sampler cohort are not inferred. Evidence is based on reviewed data only.</p>`;
}
function wireSimulator(){const el=$('simResults');if(!el)return;const draw=()=>{el.innerHTML=simChart()};document.querySelectorAll('[data-sim]').forEach(input=>{input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>{const key=input.dataset.sim;if(key==='caption_scope'){captionFilter=input.value;draw();return;}simState[key]=SIM_KEYS.some(([k])=>k===key)?Number(input.value):input.value;document.querySelectorAll('[data-sim]').forEach(other=>{if(other!==input&&other.dataset.sim===key)other.value=simState[key]});draw()})});$('simReset').onclick=()=>{Object.assign(simState,{encoder_cfg:1.6,sampler_cfg:1.6,top_k:45,sampler_steps:35,text_encoder:'bf16',dit:'fp32',pair:'dpmpp_sde_gpu / ddim_uniform',compare:'none',axis:'encoder_cfg',outcome:'accepted'});render()};draw()}
