'use strict';
/* GBR Experiment Floor. Uses the same filtered generation rows as the existing analytics. */
const EX_FIELDS=[
 ['sampler_steps','Sampling steps','number'],['encoder_cfg','Encoder CFG','number'],['sampler_cfg','Sampler CFG','number'],['top_k','Top K','number'],
 ['sampler','Sampler','category'],['scheduler','Scheduler','category'],['text_encoder','Text encoder','category'],['dit','DiT precision','category'],
 ['caption_source','Caption source','category'],['cluster','Genre cluster','category'],['version','Style / version','category'],['title','Composition','category'],
 ['caption_words','Caption words','number'],['lyrics_words','Lyric words','number'],['bpm','Estimated BPM','number'],['duration','Duration (seconds)','number'],
 ['energy_mean','Signal energy','number'],['bass_mean','Bass energy','number'],['brightness_mean','Brightness','number'],['onset_density','Onset density','number'],
 ['quality_score','Listening grade','number']
];
const EF=Object.fromEntries(EX_FIELDS.map(([id,label,type])=>[id,{id,label,type}]));
const ep={x:'sampler_steps',y:'quality_score',split:'none',mode:'auto',metric:'mean',threshold:5,selected:null};
const ECLR=['#dfb56b','#84b6a0','#cb8373','#a996cc','#e3a6c2','#81aeca','#dbc789','#c8c1a9'];
const EFESC=x=>String(x==null?'Unknown':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const efNumber=(r,k)=>{let n=Number(r[k]);return r[k]!==null&&r[k]!==''&&Number.isFinite(n)?n:null};
const efValue=(r,k)=>EF[k]?.type==='number'?efNumber(r,k):String(r[k]??'Unknown');
function efRows(){return filtered.filter(r=>Number.isFinite(+r.quality_score)&&r.quality_score!==null&&efValue(r,ep.x)!==null&&efValue(r,ep.y)!==null).slice()}
function efStats(rs){const grades=rs.map(r=>+r.quality_score).filter(Number.isFinite);return {n:grades.length,mean:grades.length?grades.reduce((a,b)=>a+b,0)/grades.length:0,accept:grades.length?grades.filter(a=>a>=4).length/grades.length:0,zero:grades.length?grades.filter(a=>a===0).length/grades.length:0}}
function efMetric(a){return ep.metric==='accept'?a.accept*100:ep.metric==='zero'?a.zero*100:a.mean}
function efMetricLabel(){return {mean:'Mean listening grade / 5',accept:'Rated 4–5 (%)',zero:'Unlistenable (%)'}[ep.metric]}
function efScale(v,a,b,l,r){return l+(v-a)/(b-a||1)*(r-l)}
function efGroup(rs,key){const m=new Map();for(const r of rs){const k=String(efValue(r,key));if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m].map(([name,items])=>({name,items,...efStats(items)}))}
function efCategories(rs,key,limit=13){const g=efGroup(rs,key).sort((a,b)=>b.n-a.n);return g.slice(0,limit)}
function efAxisKey(key){return EF[key]?.label||key}
function efVisibleType(){if(ep.mode!=='auto'){if(ep.mode==='scatter'&&(EF[ep.x].type!=='number'||EF[ep.y].type!=='number'))return 'distribution';return ep.mode;}const a=EF[ep.x].type,b=EF[ep.y].type;return a==='category'&&b==='category'?'heat':a==='number'&&b==='number'?'scatter':'distribution'}
function efOptions(selected,without=''){return EX_FIELDS.filter(a=>a[0]!==without).map(([id,label])=>`<button class="ef-choice ${selected===id?'chosen':''}" data-choose="${id}" type="button"><span class="ef-lamp"></span>${EFESC(label)}</button>`).join('')}
function efSelector(title,current,slot){return `<div class="ef-channel" data-channel="${slot}"><div class="ef-channel-kicker">${title}</div><button class="ef-knob" type="button" data-open-choose="${slot}" aria-label="Change ${title}"><span>${EFESC(efAxisKey(current))}</span><b>↕</b></button></div>`}
function efGroupSelector(){return `<button class="ef-split-button" id="efSplit"><span class="ef-lamp"></span>${ep.split==='none'?'⊕ ADD A THIRD DIMENSION':`◈ ${EFESC(efAxisKey(ep.split))}`}</button>`}
function explorerView(){const rs=efRows();const split=ep.split==='none'?[]:efCategories(rs,ep.split,8);return `<section class="ef-shell"><div class="ef-topline"><span><span class="ef-live"></span> EXPERIMENT FLOOR · GBR</span><span>${rs.length.toLocaleString()} MATCHING GENERATIONS / ${filtered.length.toLocaleString()} FILTERED</span><button type="button" id="efFilter">FILTERS ☷</button></div><div class="ef-instrument"><div class="ef-sidebar"><div class="ef-stamp">01 / RELATIONSHIP</div><div class="ef-heading">Find the<br><i>interesting bits.</i></div><p>Pick a property. Compare it to another. Add a third to expose the difference.</p>${efSelector('HORIZONTAL / FACTOR',ep.x,'x')}${efSelector('VERTICAL / RESPONSE',ep.y,'y')}<div class="ef-secondary"><span>RESULT MEASURE</span><div class="ef-toggle">${[['mean','MEAN'],['accept','4–5 %'],['zero','0 %']].map(([id,label])=>`<button type="button" data-metric="${id}" class="${ep.metric===id?'active':''}">${label}</button>`).join('')}</div></div><div class="ef-secondary"><span>EVIDENCE MINIMUM</span><div class="ef-toggle">${[1,5,10,20].map(n=>`<button type="button" data-threshold="${n}" class="${ep.threshold===n?'active':''}">${n}</button>`).join('')}</div></div><button type="button" id="efSwap" class="ef-small-action">⇄ SWAP AXES</button><button type="button" id="efReset" class="ef-small-action">↺ RESET VIEW</button></div><div class="ef-main"><div class="ef-canvas-head"><div><small>02 / SONIC EVIDENCE</small><h2>${EFESC(efAxisKey(ep.x))} <em>×</em> ${EFESC(efAxisKey(ep.y))}</h2></div><div class="ef-readout"><span>VISUAL MODE</span><select id="efMode"><option value="auto" ${ep.mode==='auto'?'selected':''}>AUTO</option><option value="scatter" ${ep.mode==='scatter'?'selected':''}>SCATTER</option><option value="distribution" ${ep.mode==='distribution'?'selected':''}>GROUPED DOTS</option><option value="heat" ${ep.mode==='heat'?'selected':''}>HEATMAP</option></select></div></div><div id="efGraphic" class="ef-graphic"></div><div class="ef-bottom"><div class="ef-breakdown">${efGroupSelector()}<div class="ef-legend">${split.map((g,i)=>`<span title="${g.n} observations"><i style="background:${ECLR[i%ECLR.length]}"></i>${EFESC(g.name)} <small>n=${g.n}</small></span>`).join('')}</div></div><div class="ef-explain" id="efExplain"></div></div></div></div><div class="ef-insights"><div><small>03 / READING THE EXPERIMENT</small><h3>What the evidence says.</h3></div><div id="efFindings" class="ef-findings"></div></div><div class="ef-foot">DOTS = INDIVIDUAL GENERATIONS · MEASUREMENTS = OBSERVED · ALL RELATIONSHIPS ARE ASSOCIATIONS, NOT PROOF OF CAUSATION</div></section><div id="efPalette" class="ef-palette" hidden><div class="ef-palette-head"><strong id="efPaletteTitle">CHOOSE A PARAMETER</strong><button id="efPaletteClose" type="button">CLOSE ×</button></div><input id="efSearch" type="search" placeholder="Find a parameter…"><div id="efChoices" class="ef-choices"></div></div>`}
function efSVGHeader(W,H,l,t,b){return `<rect x="0" y="0" width="${W}" height="${H}" fill="transparent"/><line x1="${l}" y1="${H-b}" x2="${W-18}" y2="${H-b}" stroke="#887b60" opacity=".55"/><line x1="${l}" y1="${t}" x2="${l}" y2="${H-b}" stroke="#887b60" opacity=".55"/>`}
function efScatter(rs){const W=920,H=485,L=76,T=28,B=72,R=30;
 const all=rs.length>1500?rs.filter((_,i)=>i%Math.ceil(rs.length/1500)===0):rs;
 const xs=rs.map(r=>efValue(r,ep.x)),ys=rs.map(r=>efValue(r,ep.y));let xMin=Math.min(...xs),xMax=Math.max(...xs),yMin=Math.min(...ys),yMax=Math.max(...ys);if(xMin===xMax)xMax=xMin+1;if(yMin===yMax)yMax=yMin+1;
 const x=v=>efScale(v,xMin,xMax,L,W-R),y=v=>efScale(v,yMin,yMax,H-B,T);
 const splitGroups=ep.split==='none'?[]:efCategories(rs,ep.split,8);const color=r=>{if(!splitGroups.length)return ECLR[0];const i=splitGroups.findIndex(g=>String(efValue(r,ep.split))===g.name);return i<0?'#6a6d62':ECLR[i%ECLR.length]};
 let out=efSVGHeader(W,H,L,T,B);
 for(let i=0;i<=5;i++){const value=yMin+(yMax-yMin)*i/5,py=y(value);out+=`<line x1="${L}" x2="${W-R}" y1="${py}" y2="${py}" stroke="#aa956f" opacity=".13"/><text x="${L-13}" y="${py+4}" text-anchor="end" fill="#c2b6a1" font-size="13">${Number(value.toFixed(2))}</text>`;const v=xMin+(xMax-xMin)*i/5;out+=`<text x="${x(v)}" y="${H-B+25}" text-anchor="middle" fill="#c2b6a1" font-size="13">${Number(v.toFixed(2))}</text>`}
 // deterministic displacement for discrete integer scores, not noise-based random positioning
 const discrete=rs.every(r=>Number.isInteger(+r[ep.y])&&+r[ep.y]>=0&&+r[ep.y]<=5);
 out+=all.map((r,i)=>{const py=y(efValue(r,ep.y))+(discrete?((i*37%19)-9)*.82:0);const px=x(efValue(r,ep.x));return `<circle data-ef-record="${EFESC(r.id)}" cx="${px.toFixed(2)}" cy="${py.toFixed(2)}" r="4.4" fill="${color(r)}" fill-opacity=".61" stroke="#151915" stroke-width=".55"><title>${EFESC(r.audio_file||r.title)} · ${efAxisKey(ep.x)} ${efValue(r,ep.x)} · ${efAxisKey(ep.y)} ${efValue(r,ep.y)} · grade ${r.quality_score}</title></circle>`}).join('');
 out+=`<text x="${W/2}" y="${H-12}" text-anchor="middle" fill="#d8bb83" font-size="15">${EFESC(efAxisKey(ep.x))}</text><text x="18" y="${H/2}" transform="rotate(-90 18 ${H/2})" text-anchor="middle" fill="#d8bb83" font-size="15">${EFESC(efAxisKey(ep.y))}</text>`;
 return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Scatter plot: ${EFESC(efAxisKey(ep.x))} versus ${EFESC(efAxisKey(ep.y))}">${out}</svg><p class="ef-chartnote">Each dot is an individual generation. Overlapping dots can conceal repeats. Vertical jitter is used only for discrete grades; chart values remain unchanged.</p>`}
function efDistribution(rs){let cat=EF[ep.x].type==='category'?ep.x:EF[ep.y].type==='category'?ep.y:null;let num=cat===ep.x?ep.y:ep.x;if(!cat){ // bin horizontal numeric field for quality distributions
 cat=ep.x;num=ep.y;
 const vals=rs.map(r=>+r[cat]);const min=Math.min(...vals),max=Math.max(...vals),width=(max-min||1)/8;
 rs=rs.map(r=>({...r,[cat]:(min+Math.min(7,Math.floor((+r[cat]-min)/width))*width).toFixed(2)+'–'+(min+(Math.min(7,Math.floor((+r[cat]-min)/width))+1)*width).toFixed(2)}));
 }
 const cats=efCategories(rs,cat,12);if(!cats.length)return '<div class="ef-empty">No matching values.</div>';
 const maxValue=num==='quality_score'?5:Math.max(...rs.map(r=>+r[num]));const minValue=num==='quality_score'?0:Math.min(...rs.map(r=>+r[num]));
 return `<div class="ef-distributions">${cats.map((g,j)=>{const values=g.items.map(r=>+r[num]).filter(Number.isFinite).sort((a,b)=>a-b),m=values.reduce((a,b)=>a+b,0)/values.length;const pos=v=>Math.max(0,Math.min(100,100*(v-minValue)/(maxValue-minValue||1)));const sample=values.length>75?values.filter((_,i)=>i%Math.ceil(values.length/75)===0):values;return `<div class="ef-dist-row"><span class="ef-dist-name">${EFESC(g.name)}<small>n=${g.n}</small></span><div class="ef-dist-track"><div class="ef-dist-rail"></div>${sample.map((v,i)=>`<i title="${EFESC(g.name)}: ${v}" style="left:${pos(v)}%;top:${9+(i*29%19)}px;background:${ECLR[j%ECLR.length]}"></i>`).join('')}<b style="left:${pos(m)}%" title="Mean ${m.toFixed(2)}"></b></div><strong>${m.toFixed(2)}</strong></div>`}).join('')}</div><div class="ef-scale"><span>${Number(minValue.toFixed(2))}</span><span>${EFESC(efAxisKey(num))} →</span><span>${Number(maxValue.toFixed(2))}</span></div><p class="ef-chartnote">Dots show individual observed values; gold vertical marks indicate group means. Categories are ordered by sample size, not rank.</p>`}
function efHeat(rs){const x=efCategories(rs,ep.x,10),y=efCategories(rs,ep.y,10);if(!x.length||!y.length)return '<div class="ef-empty">No matching cells.</div>';const sampleCount=rs.length;let grid=`<div class="ef-heat-wrap"><table class="ef-heat"><thead><tr><th>${EFESC(efAxisKey(ep.y))} ↓ / ${EFESC(efAxisKey(ep.x))} →</th>${x.map(a=>`<th title="${EFESC(a.name)}">${EFESC(a.name)}</th>`).join('')}</tr></thead><tbody>`;
 for(const yy of y){grid+=`<tr><th>${EFESC(yy.name)}</th>`;for(const xx of x){const intersect=rs.filter(r=>String(efValue(r,ep.x))===xx.name&&String(efValue(r,ep.y))===yy.name),s=efStats(intersect),value=efMetric(s),max=ep.metric==='mean'?5:100;grid+=`<td title="${EFESC(xx.name)} / ${EFESC(yy.name)} — n=${s.n}; mean ${s.mean.toFixed(2)}; 4–5 ${(s.accept*100).toFixed(1)}%" class="${s.n<ep.threshold?'ef-thin':''}" style="background:${s.n?`rgba(218,170,88,${(.06+.70*value/max).toFixed(2)})`:'transparent'}">${s.n?`<b>${value.toFixed(ep.metric==='mean'?2:1)}${ep.metric==='mean'?'':'%'}</b><small>n=${s.n}</small>`:'<span>·</span>'}</td>`}grid+='</tr>'}return grid+'</tbody></table></div><p class="ef-chartnote">Darker / brighter cells show '+EFESC(efMetricLabel())+'. Cells marked with low N lack sufficient observations. Empty cells are untested, not poor results. Showing '+sampleCount+' total generations.</p>'}
function efFindings(rs){const s=efStats(rs);if(!rs.length)return '<div class="ef-empty">No qualifying data; relax filters or choose other properties.</div>';
 let xGroup=EF[ep.x].type==='category'?efCategories(rs,ep.x,25):[];
 let findings=[];findings.push({name:'EVIDENCE IN VIEW',title:`${s.n.toLocaleString()} generations`,copy:`Mean grade ${s.mean.toFixed(2)} / 5 · ${(s.accept*100).toFixed(1)}% scored 4–5. These are observed ratings, not model predictions.`});
 if(xGroup.length>1){const reliable=xGroup.filter(g=>g.n>=ep.threshold).sort((a,b)=>b.mean-a.mean);if(reliable.length>=2){const best=reliable[0],worst=reliable[reliable.length-1];findings.push({name:'OBSERVED SPREAD',title:`${EFESC(best.name)} · ${best.mean.toFixed(2)}`,copy:`Highest mean among groups with at least ${ep.threshold} ratings. Difference from ${EFESC(worst.name)}: ${(best.mean-worst.mean).toFixed(2)} points. This is not a controlled effect.`})}const sparse=xGroup.filter(g=>g.n<ep.threshold);if(sparse.length)findings.push({name:'GAP DETECTED',title:`${sparse.length} thinly tested groups`,copy:`Fewer than ${ep.threshold} observations in ${sparse.slice(0,3).map(g=>EFESC(g.name)).join(', ')}. More matched experiments are needed.`})}
 else if(EF[ep.x].type==='number'){const value=rs.map(r=>efValue(r,ep.x));const lo=Math.min(...value),hi=Math.max(...value),step=(hi-lo||1)/5;const buckets=Array.from({length:5},(_,i)=>{let a=rs.filter(r=>Math.min(4,Math.floor((efValue(r,ep.x)-lo)/step))===i);return {...efStats(a),label:`${(lo+i*step).toFixed(1)}–${(lo+(i+1)*step).toFixed(1)}`}});const valid=buckets.filter(b=>b.n>=ep.threshold).sort((a,b)=>b.mean-a.mean);if(valid.length)findings.push({name:'STRONGEST OBSERVED REGION',title:`${valid[0].label}`,copy:`Mean ${valid[0].mean.toFixed(2)} / 5 across ${valid[0].n} generations. Parameter settings, caption source and genre may confound this comparison.`})}
 if(ep.split!=='none')findings.push({name:'COHORT CONTROL',title:`Split by ${efAxisKey(ep.split)}`,copy:`Check whether a trend survives within each group rather than being driven by the mixture of configurations.`});
 findings.push({name:'INTERPRETATION',title:'Observation ≠ cause',copy:'For parameter recommendations, hold song, caption, encoder, scheduler and seed design constant. Group averages alone do not isolate one parameter.'});
 return findings.slice(0,4).map(f=>`<div class="ef-finding"><small>${f.name}</small><strong>${f.title}</strong><p>${f.copy}</p></div>`).join('')}
function efDraw(){const rs=efRows(),graphic=document.getElementById('efGraphic');if(!graphic)return;const type=efVisibleType();graphic.innerHTML=type==='heat'?efHeat(rs):type==='distribution'?efDistribution(rs):EF[ep.x].type==='number'&&EF[ep.y].type==='number'?efScatter(rs):efDistribution(rs);document.getElementById('efFindings').innerHTML=efFindings(rs);document.getElementById('efExplain').textContent=type==='heat'?'CELL BRIGHTNESS = '+efMetricLabel():type==='scatter'?'EACH DOT = ONE RECORDED GENERATION':'EACH DOT = A MEASURED VALUE';graphic.querySelectorAll('[data-ef-record]').forEach(n=>n.addEventListener('click',()=>detail(n.dataset.efRecord)))}
function wireExplorer(){const q=id=>document.getElementById(id),palette=q('efPalette');let slot='x';const open=(s)=>{slot=s;q('efPaletteTitle').textContent=s==='split'?'ADD ANOTHER DIMENSION':s==='x'?'CHOOSE HORIZONTAL FACTOR':'CHOOSE VERTICAL RESPONSE';palette.hidden=false;q('efSearch').value='';fill();q('efSearch').focus()};const fill=()=>{const term=q('efSearch').value.toLowerCase();let choices=EX_FIELDS.filter(([id,label])=>(id==='none'||label.toLowerCase().includes(term)));q('efChoices').innerHTML=(slot==='split'?'<button data-choose="none" class="ef-choice">✕ NO BREAKDOWN</button>':'')+choices.map(([id,label])=>`<button type="button" data-choose="${id}" class="ef-choice ${(slot==='x'?ep.x:slot==='y'?ep.y:ep.split)===id?'chosen':''}"><span class="ef-lamp"></span>${EFESC(label)}</button>`).join('');q('efChoices').querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{let id=b.dataset.choose;if(slot==='x'&&id===ep.y||slot==='y'&&id===ep.x){const old=ep[slot];ep[slot]=id;ep[slot==='x'?'y':'x']=old}else ep[slot]=id;ep.mode='auto';palette.hidden=true;render()})};
 document.querySelectorAll('[data-open-choose]').forEach(b=>b.onclick=()=>open(b.dataset.openChoose));q('efSplit').onclick=()=>open('split');q('efPaletteClose').onclick=()=>palette.hidden=true;q('efSearch').oninput=fill;
 q('efSwap').onclick=()=>{[ep.x,ep.y]=[ep.y,ep.x];ep.mode='auto';render()};q('efReset').onclick=()=>{Object.assign(ep,{x:'sampler_steps',y:'quality_score',split:'none',mode:'auto',metric:'mean',threshold:5});render()};q('efMode').onchange=e=>{ep.mode=e.target.value;efDraw()};document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{ep.metric=b.dataset.metric;render()});document.querySelectorAll('[data-threshold]').forEach(b=>b.onclick=()=>{ep.threshold=+b.dataset.threshold;render()});q('efFilter').onclick=()=>document.body.classList.toggle('ef-filters-open');efDraw()}
